<?
define("RTL_ID","Id");
define("RTL_NOME","Nome");
define("RTL_NOMEMAE","Nomemae");
define("RTL_NOMEPAI","Nomepai");
define("RTL_DATANASCIMENTO","Datanascimento");
define("RTL_NATURALIDADE","Naturalidade");
define("RTL_ENDERECO","Endereco");
define("RTL_BAIRRO","Bairro");
define("RTL_TELEFONE","Telefone");
define("RTL_CELULAR","Celular");
define("RTL_RG","Rg");
define("RTL_ORGAO","Orgao");
define("RTL_DATAEXP","Dataexp");
define("RTL_CPF","Cpf");
define("RTL_CERTIDAORESERVISTA","Certidaoreservista");
define("RTL_TITELEITOR","Titeleitor");
define("RTL_ZONA","Zona");
define("RTL_SECAO","Secao");
define("RTL_MUNICIPIOTIT","Municipiotit");
define("RTL_CNH","Cnh");
define("RTL_CATEGORIA","Categoria");
define("RTL_DATAVALIDADE","Datavalidade");
define("RTL_TIPOSANGUINEO","Tiposanguineo");
define("RTL_ESTADOCIVIL","Estadocivil");
define("RTL_NOMEESPOSA","Nomeesposa");
define("RTL_QTDEFILHOS","Qtdefilhos");
define("RTL_COROLHOS","Corolhos");
define("RTL_CORPELE","Corpele");
define("RTL_CORCABELOS","Corcabelos");
define("RTL_RELIGIAO","Religiao");
define("RTL_GRAUESCOLARIDADE","Grauescolaridade");
define("RTL_POSSUITATUAGEM","Possuitatuagem");
define("RTL_PROFISSAOANTERIOR","Profissaoanterior");
define("RTL_FONEEMERGENCIA","Foneemergencia");
define("RTL_CURSOSREALIZADOS","Cursosrealizados");
define("RTL_CEP","Cep");
define("RTL_MUNICIPIOEND","Municipioend");
define("RTL_MATRICULA","Matricula");
define("RTL_MUNICIPIONASC","Municipionasc");
define("RTL_APELIDO","Apelido");
define("RTL_IDSTATUSGUARDA","Idstatusguarda");
define("RTL_NOMEFILHOS","Nomefilhos");
define("RTL_ARMAMENTO","Armamento");
define("RTL_IDEMPRESA","Idempresa");
define("RTL_DESCRICAO_LISTAGEM_AGENTES","Listagem de Agentes");
define("TXT_ALERT_SUCESSO_MODIFICAR","Sucesso ao modificar registro");
define("TXT_ALERT_ERRO_OPERACAO","Erro ao executar operação");
define("TXT_ALERT_SUCESSO_OPERACAO","Sucesso ao executar operação");
define("TXT_ALERT_SUCESSO_ADICIONAR","Sucesso ao Adicionar registro");
define("TXT_CONFIRME_DELETE_REGISTROS","Deseja realmente remover este(s) registro(s)?");
define("TXT_CONFIRMACAO_DELETE_REGISTROS","Registros foram excluidos com exito");
define("TXT_ERRO_DELETAR_REGISTROS","Erro ao Excluir registros");
define("TXT_ERRO_NENHUM_REGISTRO_SELECIONADO","Por favor, selecione itens para serem excluidos");
define("TXT_ATENCAO","Atenção");
define("TXT_PREENCHA_CAMPOS_OBRIGATORIOS","Por favor preencher todos os campos obrigatórios");
define("RTL_AGENTES","Agentes");
define("RTL_MODIFICAR_AGENTES","Modificar Agentes");
define("RTL_ADICIONAR_AGENTES","Adicionar Agentes");
