<?
define("RTL_ID", "Id");
define("RTL_ID_GRUPO", "Id Grupo");
define("RTL_QUESTAO_TIPO", "Questao Tipo");
define("RTL_TEXTO", "Texto");
define("RTL_EXCLUIDO", "Excluido");
define("RTL_DESCRICAO_LISTAGEM_APP_QUESTAO", "Listagem de App Questao");
define("TXT_ALERT_SUCESSO_MODIFICAR", "Sucesso ao modificar registro");
define("TXT_ALERT_ERRO_OPERACAO", "Erro ao executar operação");
define("TXT_ALERT_SUCESSO_OPERACAO", "Sucesso ao executar operação");
define("TXT_ALERT_SUCESSO_ADICIONAR", "Sucesso ao Adicionar registro");
define("TXT_CONFIRME_DELETE_REGISTROS", "Deseja realmente remover este(s) registro(s)?");
define("TXT_CONFIRMACAO_DELETE_REGISTROS", "Registros foram excluidos com exito");
define("TXT_ERRO_DELETAR_REGISTROS", "Erro ao Excluir registros");
define("TXT_ERRO_NENHUM_REGISTRO_SELECIONADO", "Por favor, selecione itens para serem excluidos");
define("TXT_ATENCAO", "Atenção");
define("TXT_PREENCHA_CAMPOS_OBRIGATORIOS", "Por favor preencher todos os campos obrigatórios");
define("RTL_APP_QUESTAO", "Questão");
define("RTL_MODIFICAR_APP_QUESTAO", "Modificar App Questao");
define("RTL_ADICIONAR_APP_QUESTAO", "Adicionar App Questao");
define("RTL_TIPO_QUESTAO", "Tipo de questão");
define("RTL_RESPOSTAS", "Respostas");
define("RTL_ADICIONAR_RESPOSTA", "Adicionar nova resposta");
define("TXT_VALIDACAO_REMOCAO_RESPOSTAS", "Você não pode remover todas as respostas");