<?
define("RTL_ID", "Id");
define("RTL_ID_GRUPO", "Id Grupo");
define("RTL_ID_QUESTIONARIO", "Id Questionario");
define("RTL_TITULO", "Titulo");
define("RTL_DESCRICAO", "Descricao");
define("RTL_DATA_HORA_CADASTRO", "Data Hora Cadastro");
define("RTL_EXCLUIDO", "Excluido");
define("RTL_DESCRICAO_LISTAGEM_APP_PESQUISA", "Listagem de App Pesquisa");
define("TXT_ALERT_SUCESSO_MODIFICAR", "Sucesso ao modificar registro");
define("TXT_ALERT_ERRO_OPERACAO", "Erro ao executar operação");
define("TXT_ALERT_SUCESSO_OPERACAO", "Sucesso ao executar operação");
define("TXT_ALERT_SUCESSO_ADICIONAR", "Sucesso ao Adicionar registro");
define("TXT_CONFIRME_DELETE_REGISTROS", "Deseja realmente remover este(s) registro(s)?");
define("TXT_CONFIRMACAO_DELETE_REGISTROS", "Registros foram excluidos com exito");
define("TXT_ERRO_DELETAR_REGISTROS", "Erro ao Excluir registros");
define("TXT_ERRO_NENHUM_REGISTRO_SELECIONADO", "Por favor, selecione itens para serem excluidos");
define("TXT_ATENCAO", "Atenção");
define("TXT_PREENCHA_CAMPOS_OBRIGATORIOS", "Por favor preencher todos os campos obrigatórios");
define("RTL_APP_PESQUISA", "App Pesquisa");
define("RTL_MODIFICAR_APP_PESQUISA", "Modificar App Pesquisa");
define("RTL_ADICIONAR_APP_PESQUISA", "Adicionar App Pesquisa");
define("RTL_APLICAR_PESQUISA", "Aplicar pesquisa");
define("RTL_QUESTIONARIO", "Questionário");
define("RTL_PLACEHOLDER_BUSCAR_USUARIO", "Busque usuários pelo nome");
define("RTL_APLICAR_PARA", "Aplicar para");
define("TXT_INFORMACOES_PESQUISA", "As pesquisas são salvas pergunta a pergunta, e você pode fechá-la quando quiser para continuar mais tarde.");
define("RTL_RESPONDER", "Responder");
define("RTL_PERGUNTA", "Pergunta");
define("TXT_FIM_PERGUNTAS", "Obrigado por responder esse questionário");
define("RTL_TITULO_FIM_PERGUNTAS", "Questionário finalizado");