<?php
define("RTL_CONTROLE_VISITA", "Controle de visitas");
define("RTL_RELATORIO", "Relatório");
define("RTL_BAIRRO", "Bairro");
define("RTL_CELULAR", "Celular");
define("RTL_CEP", "CEP");
define("RTL_CIDADE", "Cidade");
define("RTL_COMPLEMENTO", "Complemento");
define("RTL_CPF_CNPJ", "Cpf Cnpj");
define("RTL_EMAIL", "Email");
define("RTL_ID", "Id");
define("RTL_ENDERECO", "Endereço");
define("RTL_NEXTEL", "Nextel");
define("RTL_NOME", "Nome");
define("RTL_NUMERO", "Número");
define("RTL_TELEFONE", "Telefone");
define("RTL_UF", "UF");
define("RTL_TIPO_PRODUTO", "Tipo do produto");
define("RTL_RESPONSAVEL", "Responsavel");
define("RTL_LATITUDE", "Latitude");
define("RTL_LONGITUDE", "Longitude");
define("RTL_ADICIONAR_CLIENTE", "Adicionar cliente");
define("RTL_ADICIONAR_TIPO_PRODUTO", "Adicionar tipo de produto");
define("TXT_ALERT_SUCESSO_MODIFICAR", "Operação executada com sucesso");
define("RTL_AGENDAR_VISITA", "Agendar visita");
define("RTL_GERAR", "Gerar");
define("RTL_PDF", "PDF");
define("RTL_IMPRIMIR", "Imprimir");
define("RTL_EXCEL", "Excel");
define("RTL_CLIENTE", "Cliente");
define("RTL_VENDEDOR_USUARIO", "Vendedor/Usuário");
define("RTL_TIPO_VISITA", "Tipo de visita");
define("RTL_FORMA_DE_VISITA", "Forma de visita");
define("RTL_VISITA_CONTINUA", "Visita contínua?");
define("RTL_SIM", "Sim");
define("RTL_NAO_APENAS_UMA_VEZ", "Não, apenas uma vez.");
define("RTL_CONCORRENTE", "Concorrente");
define("RTL_ADICIONAR", "Adicionar");
define("RTL_PRESENCIAL", "Presencial");
define("RTL_FINALIZAR_VISITAS", "Finalizar visitas");
define("RTL_MODIFICAR_CLIENTE", "Modificar cliente");
define("RTL_SEQUENCIA_REAL", "Sequência real");
define("RTL_SEQUENCIA_PROGRAMADA", "Sequência programada");
define("RTL_PERMANENCIA", "Permanência");
define("RTL_AGENDAR ", "Agendar");
define("RTL_FINALIZAR ", "Finalizar");

define("RTL_CALENDARIO", "Calendário");
define("RTL_CAMPOS_FORMULARIO", "Campos do formulário");
define("RTL_FINALIZAR_VISITA", "Finalizar visita");
define("RTL_LISTAGEM_FINALIZAR_VISITAS", "Listagem de visitas");

define("TXT_TUTORIAL_ADICIONAR", "Adicione clientes ao controle de visitas. Clique em próximo para abrir o formulário.");
define("TXT_TUTORIAL_TIPO_PRODUTO", "Selecione o tipo do produto. Caso não encontre o desejado, clique no '+' para adicionar um novo tipo de produto.");
define("TXT_TUTORIAL_AGENDAR_VISITA", "Aqui você pode agendar visitas aos clientes. Clique em próximo para abrir a agenda e continuarmos o tutorial.");
define("TXT_TUTORIAL_CALENDARIO", "Esse é o seu calendário de visitas. Deixe o mouse em cima de alguma visita para obter mais informações ou clique nela modificá-la.");
define("TXT_TUTORIAL_CAMPOS_FORMULARIO", "Preencha todos os campos do formulário de acordo com a visita.");
define("TXT_TUTORIAL_ADICIONAR_VISITA", "Clique para adicionar a visita a agenda.");
define("TXT_TUTORIAL_FINALIZAR_VISITA", "Agora que temos uma visita agendada, podemos verificar a situação dela e finalizá-la se necessário.");
define("TXT_TUTORIAL_LISTAGEM_FINALIZAR_VISITAS", "Aqui temos uma listagem de todas as visitas pendentes ou reagendadas.");
define("TXT_TUTORIAL_ACAO_FINALIZAR_VISITAS", "Clicando no - em vermelho, você poderá reagendar a visita ou finalizá-la.");
define("TXT_MSG_BUSCA", "Colunas de Busca: Nome.");