<?php
define("RTL_JORNADA_TRABALHO", "Jornada de Trabalho");
define("RTL_ADICIONAR_JUSTIFICATIVA", "Adicionar Justificativa");
define("RTL_JORNADA_HORAS", "Jornada (horas)");
define("RTL_JORNADA_MINUTOS", "Jornada (minutos)");
define("RTL_ADICIONAR_OBSERVACAO", "Adicionar Justificativa");
define("RTL_TIPO_MACRO", "Tipo da macro");
define("RTL_TUTORIAL_HORAS_MINUTOS", "Jornada (horas/mintuos).");
define("RTL_INFORMACOES_ACIONAMENTO", "Informações de acionamento");
define("RTL_TOTAL_GERAL", "Total geral");
define("RTL_TEMPO_REFEICAO", "Tempo de refeição");
define("RTL_TEMPO_CARGA_DESCARGA", "Tempo de carga/descarga");
define("RTL_CARGA_DESCARGA", "Carga/descarga");
define("RTL_TEMPO_DESCANSO", "Tempo de descanso");
define("RTL_TEMPO_JORNADA_SEM_DESCONTOS", "Tempo de jornada (sem descontos)");
define("RTL_TEMPO_JORNADA_COM_DESCONTOS", "Tempo de jornada (com descontos)");
define("RTL_TEMPO_DESLOCAMENTO", "Tempo de deslocamento");
define("RTL_TEMPO_TRABALHO", "Tempo de trabalho");
define("RTL_TEMPO_VIAGEM", "Tempo de viagem");
define("RTL_TEMPO_ESPERA", "Tempo de espera");
define("RTL_TEMPO_ADICIONAL_NOTURNO", "Tempo de adicional noturno");
define("RTL_HORA_EXTRA", "Hora extra");
define("RTL_DESCONTAR_CARGA_DESCARGA", "Descontar carga/descarga da jornada?");
define("RTL_SEM_HORA_EXTRA", "sem hora extra.");
define("RTL_MOVIMENTO", "Em movimento");
define("RTL_ASSINATURA_MOTORISTA", "Assinatura do motorista");
define("RTL_ASSINATURA_RH", "Assinatura do RH");
define("TXT_TUTORIAL_MOTORISTA", "Campo de busca de motorista.");
define("TXT_TUTORIAL_DATA_HORA_INICIAL", " Selecione a data inicial que deseja visualizar.");
define("TXT_TUTORIAL_DATA_HORA_FINAL", " Selecione a data final que deseja visualizar.");
define("TXT_TUTORIAL_VISUALIZACAO", "Selecione o tipo de visualização que deseja.");
define("TXT_TUTORIAL_HORAS", "Jornada de trabalho.");
define("TXT_TUTORIAL_JUSTIFICATIVA", "Adicione uma justificativa para mensagens que não foram enviadas.");
define("TXT_AVISO_INTERVALO", "Caso falte algum FIM ou INÍCIO, ou algum deles seja inválido, todos os cálculos que usem o intervalo com falha estarão sujeitos a erros.");
define("TXT_ERRO_MOTORISTA", "Selecione um motorista.");
define("TXT_AVISO_JORNADA_MINUTOS", "O campo de jornada (minutos) está vazio. O valor utilizado será o padrão de 0 minutos");
define("TXT_AVISO_JORNADA_HORAS", "O campo de jornada (horas) está vazio. O valor utilizado será o padrão de 8 horas");
define("TXT_ERRO_GRUPO", "Selecione um grupo para realizar a pesquisa");
define("TXT_ERRO_DATA", "Selecione uma data para realizar a pesquisa");
define("TXT_ERRO_MACRO", "Selecione uma macro para realizar a pesquisa");