<?php
define("RTL_MACRO", "Macros");
define("RTL_ADICIONAR_MACRO", "Adicionar macro");
define("RTL_MODIFICAR_MACRO", "Modificar macro");
define("RTL_TELA", "Tela");

define("RTL_TIPO_CAMPO", "Tipo do campo");
define("RTL_DESCRICAO_CAMPO", "Descrição do campo");
define("RTL_ROTULO", "Rótulo");
define("RTL_TAMANHO_CAMPO", "Tamanho do campo");
define("RTL_REMOVER", "Remover");
define("RTL_NOME_TELA", "Nome da tela");
define("RTL_ADICIONAR_TELA", "Adicionar tela");
define("RTL_MODIFICAR_TELA", "Modificar tela");
define("RTL_ADICIONAR_CAMPO", "Adicionar campo");
define("RTL_DECIMAL", "Decimal");
define("RTL_NUMERICO", "Numérico");
define("RTL_TEXTO", "Texto");
define("RTL_ADICIONAR_ABA", "Adicionar aba");
define("RTL_PLACEHOLDER_CAMPO_ROTULO", "Campo para texto livre");
define("RTL_LINKS", "Links");
define("RTL_SLOT", "Slot");
define("RTL_TELA_DESTINO", "Tela de destino");
define("RTL_EDITAR_TELAS", "Editar telas");
define("TXT_ADICIONE_CAMPOS", "Adicione campos para salvar a tela");
define("TXT_CAMPO_MUITO_LONGO", "O texto e o tamanho do campo não pode ultrapassar 40 caracteres na linha: ");
define("TXT_TAMANHO_ZERO", "O tamanho do campo não pode ser zero na linha: ");
define("TXT_LIMITE_CAMPOS_ATINGIDO", "Limite de campos atingido.");
define("RTL_MENSAGEM_TEXTO_LIVRE", "Mensagem de texto livre");
define("RTL_MENSAGENS_ENVIADAS", "Mensagens enviadas");
define("RTL_MENSAGENS_RECEBIDAS", "Mensagens recebidas");
define("TXT_ABA_ABERTA", "Já existe uma aba aberta. Feche-a antes de abrir outra.");
define("RTL_COPIAR_TELA", "Copiar tela existente");
define("TXT_TUTORIAL_MASCARA_DECIMAL", "O valor 5.3 para esse campo representará um número com 5 caracteres antes da vírgula e 3 depois, por exemplo: 12345,123.<br/><br/>Utilize . (ponto) para separar os decimais.<br/></br>A vírgula conta como um caractere.");
define("TXT_CAMPOS_PRECISAM_TRES_CARACTERES", "Os campos dos atalhos precisam de 3 caracteres, obrigatoriamente");
define("RTL_SELECIONE_TEMPLATE", "Selecione o template");
define("RTL_MENU_PRINCIPAL", "Menu principal");
define("RTL_ESPELHAR_DESCRICAO_ROTULO", "Espelhar descrição e rótulo?");
define("TXT_LINKS_DUPLICADOS", "Não utilize mais de um link para a mesma tela");
define("RTL_PROXIMA_TELA", "Próxima tela");
define("RTL_TORNAR_PRIORITARIA", "Torná-la prioritária?");
define("RTL_OMITIR_MENSAGEM", "Omitir mensagem?");
define("RTL_TELA_PRIORITARIA", "Tela prioritária");
define("RTL_ESTADO_ENTRADAS_SAIDAS", "Estado das Entradas e Saídas");
define("RTL_ESTADO_SATELITAL", "Estado do Satelital");
define("RTL_LOGOFF_MOTORISTA", "Realizar logoff do motorista?");
define("RTL_LOGIN_MOTORISTA", "Login de motorista");
define("RTL_SENHA_MOTORISTA", "Senha de motorista");
define("RTL_ATUAR_SOBRE_PORTA", "Atuar sobre porta pré-selecionada");
define("RTL_GERAR_CONTRA_SENHA", "Gerar contra-senha para saídas");
define("RTL_VINCULAR_BIBLIOTECA_MOTORISTAS", "Vincular biblioteca de motoristas");
define("RTL_VINCULAR_ACAO_EMBARCADA", "Vincular ação embarcada");

define("TXT_TUTORIAL_COPIAR_TELA", "Copie padrão de uma tela existente");
define("TXT_TUTORIAL_LINKS", "Adiciona atalho para outras telas");
define("TXT_NOME_TELA", "Campo para nomear a tela");
define("TXT_TUTORIAL_ADICIONAR", "Botão onde pode ser adicionado novas macros.");
define("TXT_TUTORIAL_TIPO_CAMPO", "Selecione o tipo do campo. Para campos de apresentação que contém apenas texto, utilize o tipo 'Rótulo'.");
define("TXT_TUTORIAL_DESCRICAO_CAMPO", "Descrição para controle interno do sistema. Não afeta o teclado.");
define("TXT_TUTORIAL_ROTULO_CAMPO", "Texto que irá aparecer no teclado para esse campo.");
define("TXT_TUTORIAL_TAMANHO_CAMPO", "Tamanho da linha digitável desse campo. O limite do teclado é de 40 caracteres por linha. Soma-se o tamanho do rótulo com o tamanho da linha digitável para validar esse tamanho.");
define("TXT_CAMPO_EXCLUSIVO", "Existe um campo exclusivo nessa tela. Apenas campos de rótulo são permitidos em conjunto aos campos exclusivos");
define("TXT_CAMPO_EXCLUSIVO_DUPLICADO", "Campo exclusivo duplicado");
define("TXT_MSG_BUSCA", "Colunas de Busca: Tipo, Nome e Descrição.");
define("TXT_OMITIR_MENSAGEM_LOGOFF", "Não é permitido realizar logoff do motorista e omitir a mensagem na mesma tela");
define("TXT_CAMPO_EXCLUSIVO_OMITIR_LOGOFF", "Não é permitido realizar logoff do motorista ou omitir a mensagem na mesma tela onde existe campos exclusivos");

