<?
define("RTL_ID", "Id");
define("RTL_ID_MANUTENCAO_SINISTRO", "Id Manutencao Sinistro");
define("RTL_NOME", "Nome");
define("RTL_ARQUIVO", "Arquivo");
define("RTL_EXCLUIDO", "Excluido");
define("RTL_DESCRICAO_LISTAGEM_MANUTENCAO_SINISTRO_FOTO", "Listagem de Manutencao Sinistro Foto");
define("TXT_ALERT_SUCESSO_MODIFICAR", "Sucesso ao modificar registro");
define("TXT_ALERT_ERRO_OPERACAO", "Erro ao executar operação");
define("TXT_ALERT_SUCESSO_OPERACAO", "Sucesso ao executar operação");
define("TXT_ALERT_SUCESSO_ADICIONAR", "Sucesso ao Adicionar registro");
define("TXT_CONFIRME_DELETE_REGISTROS", "Deseja realmente remover este(s) registro(s)?");
define("TXT_CONFIRMACAO_DELETE_REGISTROS", "Registros foram excluidos com exito");
define("TXT_ERRO_DELETAR_REGISTROS", "Erro ao Excluir registros");
define("TXT_ERRO_NENHUM_REGISTRO_SELECIONADO", "Por favor, selecione itens para serem excluidos");
define("TXT_ATENCAO", "Atenção");
define("TXT_PREENCHA_CAMPOS_OBRIGATORIOS", "Por favor preencher todos os campos obrigatórios");
define("RTL_MANUTENCAO_SINISTRO_FOTO", "Manutencao Sinistro Foto");
define("RTL_MODIFICAR_MANUTENCAO_SINISTRO_FOTO", "Modificar Manutencao Sinistro Foto");
define("RTL_ADICIONAR_MANUTENCAO_SINISTRO_FOTO", "Adicionar Manutencao Sinistro Foto");
