<?
define("RTL_ABRIR_USUARIO", "Abrir Usuário");
define("RTL_ADICIONAR_USUARIO", "Adicionar Usuário");
define("RTL_BAIRRO", "Bairro");
define("RTL_CELULAR", "Celular");
define("RTL_CEP", "CEP");
define("RTL_CIDADE", "Cidade");
define("RTL_COMPLEMENTO", "Complemento");
define("RTL_CONFIRMAR_SENHA", "Confirmar Senha");
define("RTL_CPF_CNPJ", "Cpf Cnpj");
define("RTL_DATA_HORA_CADASTRO", "Data Hora Cadastro");
define("RTL_DATA_HORA_EXPIRADO", "Data Hora Expirado");
define("RTL_DESCRICAO_LISTAGEM_USUARIO", "Listagem de usuário");
define("RTL_EMAIL", "Email");
define("RTL_EXPIRA_EM", "Expira em");
define("RTL_FOTO", "Foto");
define("RTL_ID", "Id");
define("RTL_ID_ENDERECO", "Id Endereco");
define("RTL_ID_FUSO_HORARIO", "Id Fuso Horario");
define("RTL_ID_GRUPO", "Id Grupo");
define("RTL_ID_NEXTEL", "ID Nextel");
define("RTL_LISTAGEM_USUARIO", "Listagem de Usuários");
define("RTL_LOGRADOURO", "Logradouro");
define("RTL_MASTER", "Master");
define("RTL_MENSAGEM", "Mensagem");
define("RTL_MODIFICAR_USUARIO", "Modificar Usuário");
define("RTL_NAO", "Não");
define("RTL_NEXTEL", "Nextel");
define("RTL_NOME", "Nome");
define("RTL_NOME_FUSO_HORARIO", "Horário de...");
define("RTL_NUMERO", "Número");
define("RTL_OBSERVACAO", "Observação");
define("RTL_PATCH_ATUALIZACAO", "Patch Atualizacao");
define("RTL_PERGUNTA_SENHA", "Pergunta Senha");
define("RTL_REFERENCIA", "Referência");
define("RTL_REMOVER_FOTO", "Remover Foto");
define("RTL_RESPOSTA_SENHA", "Resposta Senha");
define("RTL_SENHA", "Senha");
define("RTL_SENHA_PROVISORIA", "Senha Provisoria");
define("RTL_SIM", "Sim");
define("RTL_TELEFONE", "Telefone");
define("RTL_TIPO_ACESSO", "Tipo Acesso");
define("RTL_UF", "UF");
define("RTL_USUARIO", "Usuário");
define("TXT_ALERT_SUCESSO_ADICIONAR", "Sucesso ao Adicionar registro");
define("TXT_ALERT_SUCESSO_MODIFICAR", "Sucesso ao modificar registro");
define("TXT_CEP_OBRIGATORIO", "Um CEP deve ser digitado");
define("TXT_CONFIRMAR_REMOCAO_FOTO", "Deseja realmente remover a foto desse usuário?");
define("TXT_EMAIL_COMO_USUARIO", "O email será utilizado como login para o usuário.");
define("TXT_FORMATO_FOTO_INVALIDO", "Formato Inválido, por favor somente extensões (Jpeg,Jpg,Png,BMP)");
define("TXT_LETRA_NUMERO_SENHA", "Sua senha precisa de pelo menos 1 letra e um número.");
define("TXT_PREENCHA_CAMPOS_OBRIGATORIOS", "Por favor preencher todos os campos obrigatórios");
define("TXT_SENHA_AINDA_INVALIDA", "A sua senha ainda não é válida!");
define("TXT_SENHA_CURTA", "Sua senha é curta demais!");
define("TXT_SENHA_INCOMPATIVEL", "A senha e a confirmação não são iguais!");
define("TXT_SENHA_INVALIDA", "Sua senha precisa de pelo menos 1 número e 1 letra.");
define("TXT_SENHAS_DIFERENTES", "As senhas são diferentes!");
define("TXT_TAMANHO_SENHA", "Sua senha precisa ter entre 8 e 32 caracteres.");
define("TXT_USUARIO_EXISTENTE", "Esse email já existe em outro usuário ativo. Favor escolher outro.");
define("TXT_USUARIO_INVALIDO", "Usuário inválido.");
define("TXT_USUARIO_TAMANHO_INVALIDO", "Use um login que tenha entre 3 e 30 caracteres.");
define("TXT_CAMPO_EMAIL_OBRIGATORIO", "Email inválido, favor digitar um email válido. Ex. example@example.com.br");