<?
define("RTL_REMOVER_GRID", "Remover do grid");
define("RTL_CONFIGURACOES", "Configurações");
define("RTL_BUSCAR_VEICULOS", "Buscar veículos");
define("RTL_ATUALIZANDO_EM", "Atualizando em ");
define("RTL_MONITORAMENTO", "Monitoramento");
define("RTL_VER_NO_MAPA", "Ver no mapa");
define("RTL_PONTO_INTERESSE_CATEGORIA", "Categoria de ponto de interesse");
define("RTL_CADASTRAR_POSICAO_COMO_PONTO_INTERESSE", "Cadastrar posição como ponto de interesse");
define("RTL_PLACEHOLDER_EM_METROS", "em metros.");
define("RTL_LOCALIZAR_PROXIMIDADE", "Localizar proximidades");
define("RTL_PROXIMIDADE_DE", "Veículos próximos a");
define("RTL_GRUPO_VEICULO", "Grupo de veículos");
define("RTL_GRUPO_SISTEMA", "Buscar por Grupos");
define("RTL_AGRUPAMENTO_VEICULO", "Buscar Por Agrupamento");
define("RTL_TODOS_EVENTOS", "Todos os eventos");
define("RTL_INTERVALO_ATUALIZACAO", "Intervalo de atualização");
define("RTL_ZERAR_GRID", "Zerar grid");
define("RTL_TRAFEGO", "Tráfego");
define("RTL_TEMAS", "Temas");
define("RTL_PESQUISAR_GRUPO", "Pesquisar grupos");
define("RTL_PLACEHOLDER_BUSCA_VEICULO", "Digite algo para iniciar a busca dos veículos.");
define("RTL_POSICAO_PERIODO", "Posição Período");
define("RTL_INFO_VEICULO", "Informações do veículo");
define("RTL_MENSAGENS", "Mensagens");
define("RTL_LOCALIZAR_GRID", "Localizar no grid");
define("RTL_ATUACAO", "Atuação");
define("RTL_INFO_MOTORISTA", "Informações do motorista");
define("RTL_INICIAR_ASSISTENTE", "Iniciar assistente");
define("RTL_MAXIMIZAR_MINIMIZAR", "Maximizar/Minimizar");
define("RTL_ATUALIZAR", "Atualizar grid");
define("RTL_CONTADOR_VEICULOS", "Contador de veículos");
define("RTL_DISTANCIA_ROTA", "Distância da rota");
define("RTL_MINIMIZAR", "Minimizar grid");
define("RTL_CONFIGURACAO", "Configuração do grid");
define("RTL_TENSAO", "Tensão");
define("RTL_BARRA_JANELA", "Barra/Janela");
define("RTL_CLIQUE_ACOMPANHAR", "Clique para acompanhar");
define("RTL_ATUALIZAR_LOGRADOURO", "Atualizar logradouro");
define("RTL_MOSTRAR_PLACA", "Clique para mostrar a Placa/Ícone");
define("RTL_ATUALIZAR_MAPA_AUTOMATICAMENTE", "Marque para centralizar o mapa automaticamente");
define("TXT_VEICULO_SEM_POSICAO_VALIDA", "Veículo sem posição válida");
define("RTL_FINALIZAR_EVENTO", "Finalizar evento");
define("RTL_EVENTO_CRITICO", "Evento crítico");
define("RTL_LISTAR_TIPO", "Listar tipo");
define("RTL_EVENTOS_VEICULOS_MONITORADOS", "Eventos de veículos monitorados");


define("RTL_PLACEHOLDER_BUSCA_PONTO_INTERESSE", "Digite algo para buscar pontos de interesse");
define("RTL_PLACEHOLDER_BUSCA_CERCA_POLIGONO", "Digite algo para buscar cercas polígonos");
define("RTL_PLACEHOLDER_BUSCA_CERCA_ROTAS", "Digite algo para buscar cercas de rotas");
define("RTL_VER_MAPA", "Ver no mapa");
define("RTL_REMOVER", "Remover todos");
define("RTL_DISTANCIA", "Distância total");

define("TXT_SEM_MOTORISTA", "Esse veículo não possui motorista.");
define("TXT_RAIO_VAZIO", "O raio deve ser preenchido");
define("TXT_TUTORIAL_BUSCAR_VEICULO_UNICO", "Clique para abrir a busca de veículo único. Digite a placa que deseja e tecle enter para visualizar no mapa.");
define("TXT_TUTORIAL_MENU", "Clique aqui para acessar todas as opções da Central de Monitoramento.");
define("TXT_TUTORIAL_BUSCAR_VEICULOS_MULTIPLOS", "Aqui é possível selecionar vários veículos e visualizá-los simultaneamente no mapa.");
define("TXT_TUTORIAL_TODOS_EVENTOS", "Um atalho para verificar todos os eventos em aberto.");
define("TXT_TUTORIAL_ATUALIZAR_GRID", "Atualize as informações de todos os veículos que estão sendo visualizados, no mapa e no grid.");
define("TXT_TUTORIAL_CONFIGURAR_GRID", "Configure as colunas que gostaria de ver na listagem dos veículos, assim como o intervalo de atualização automático do grid.");
define("TXT_TUTORIAL_TRAFEGO", "Adiciona uma camada de informações de tráfego ao mapa. Clique para ativar/desativar.");
define("TXT_TUTORIAL_PONTO_INTERESSE", "Selecione categorias de pontos de interesse para visualizar no mapa suas informações e locais.");
define("TXT_TUTORIAL_TEMPORIZADOR_ATUALIZACAO", "Temporizador automático de atualização do grid/mapa.");
define("TXT_TUTORIAL_TEMAS", "Adicione uma camada de ícones personalizada em cima do mapa.");
define("TXT_TUTORIAL_ZERAR_GRID", "Remova todos os veículos do mapa/listagem.");
define("TXT_TUTORIAL_GRUPO_VEICULO", "Selecione grupos de veículos a partir dos grupos do sistema ou agrupamento de veículos.");
define("TXT_TUTORIAL_TEMPO_ATUALIZACAO", "Mude o tempo de atualização automático do grid/mapa. Também acessível pelas configurações.");
define("TXT_TUTORIAL_MAXIMIZAR_MINIMIZAR", "Clique para maximizar ou minimizar o grid.");
define("TXT_TUTORIAL_LOCALIZA_ENDERECO", "Clique para localizar endereços e gerar rotas.");
define("TXT_TUTORIAL_DISTANCIA", "Distância em KM da rota gerada a partir da pesquisa de endereço.");
define("TXT_ERRO_TIMER", "Valor escolhido para o temporizador é inferior ao valor mínimo");
define("RTL_EM_PANICO", "Em pânico");
define("RTL_NORMAL", "Normal");
define("RTL_BLOQUEADO", "Bloqueado");
define("RTL_DESBLOQUEADO", "Desbloqueado");
define("RTL_LIGADO", "Ligado");
define("RTL_DESLIGADO", "Desligado");
define("RTL_TENSAO", "Tensão");


