<?php
define("RTL_ADICIONAR_FOTO", "Anexos");
define("RTL_ATUALIZANDO_EM", "Atualizando em");
define("RTL_CARACTERISTICAS_VEICULO", "Característica do veículo");
define("RTL_CHAMADOS", "Chamados"); //traduzir para numero de emergência local
define("RTL_DADOS_VEICULO", "Dados do veículo");
define("RTL_DESCRICAO_EVENTO", "Descrição do evento");
define("RTL_DESCRICAO_ROUBO", "Descrição do roubo");
define("RTL_EM_ANDAMENTO", "Em andamento");
define("RTL_FINALIZAR_ROUBO", "Finalizar roubo");
define("RTL_HISTORICO_EVENTO", "Histórico do evento");
define("RTL_HISTORICO_ROUBO", "Histórico do roubo");
define("RTL_HISTORICO_ROUBO_UPPER", "HISTORICO DO ROUBO");
define("RTL_INFORMACOES_CLIENTE_UPPER", "INFORMAÇÕES DO CLIENTE");
define("RTL_INFORMACOES_EVENTO_UPPER", "INFORMAÇÕES DO EVENTO");
define("RTL_INFORMACOES_VEICULO_UPPER", "INFORMAÇÕES DO VEÍCULO");
define("RTL_INFORMACOES_VITIMA_UPPER", "INFORMAÇÕES DAS VÍTIMAS");
define("RTL_LIGOU_EMERGENCIA", "Ligou 190"); //traduzir para numero de emergência local
define("RTL_LIGOU_PRONTA_RESPOSTA", "Ligou pronta resposta");
define("RTL_MAPA_ULTIMAS_POSICOES", "MAPA DAS ULTIMAS POSIÇÕES");
define("RTL_NAO_ENCONTRADO", "Não encontrado");
define("RTL_NOME_INFORMANTE", "Nome do informante");
define("RTL_NOME_POLICIAL", "Nome do policial");
define("RTL_NOVO_ROUBO", "Novo roubo");
define("RTL_PEGOU_TELEFONE_INFORMANTE", "Pegou telefone do informante");
define("RTL_PEGOU_TELEFONE_POLICIAL", "Pegou telefone do policial");
define("RTL_PRONTA_RESPOSTA_ATIVADA", "Pronta resposta ativada");
define("RTL_RECUPERADO", "Recuperado");
define("RTL_ROUBO", "Roubo");
define("RTL_ROUBO_ANDAMENTO", "Roubo em andamento");
define("RTL_ROUBO_FINALIZADO", "Roubo finalizado");
define("RTL_SUSPEITA_ROUBO", "Suspeita de roubo");
define("RTL_TELEFONE_INFORMANTE", "Telefone do informante");
define("RTL_TELEFONE_POLICIAL", "Telefone do policial");
define("RTL_ULTIMAS_POSICOES", "Últimas posições");
define("RTL_ULTIMAS_POSICOES_UPPER", "ÚLTIMAS POSIÇÕES");
define("RTL_VEICULO_CARREGADO", "Veiculo carregado");
define("RTL_VITIMA_PERIGO", "Vítima em perigo");
define("RTL_DADOS_MOTORISTA", "Dados do motorista");
define("RTL_TELA_CENTRAL", "Tela central");
define("RTL_ATUACAO", "Atuação");
define("RTL_MENSAGENS", "Mensagens");
define("RTL_ARQUIVOS", "Anexos");
define("RTL_DOWNLOAD", "Download");
define("ROTULO_FORMATO", "Formato");
define("RTL_SUBIR_ARQUIVO", "Subir Arquivos");
define("RTL_SELECIONAR_FOTOS", "Selecione a foto");
define("RTL_CONTATOS_CLIENTE", "Contatos do cliente");
define("RTL_PRONTA_RESPOSTA", "Pronta resposta");
define("RTL_ABRIR_CHAMADO", "Abrir chamado");
define("RTL_ANEXOS_UPADOS", "Listagem de uploads");
define("RTL_MENSAGEM_60", "O intervalo de atualização foi alterado para 60 segundos");
define("RTL_MENSAGEM_NORMAL_60", "O intervalo de atualização foi alterado para o padrão");
define("RTL_IMPRIMIR_RELATORIO", "Imprimir relatório");
define("RTL_PERDA_SINAL", "Perda de sinal");
define("RTL_SUSPEITA_ROUBO", "Suspeita de roubo");
define("RTL_ROUBO_CONFIRMADO", "Roubo confirmado");
define("RTL_FURTO_CONFIRMADO", "Furto confirmado");
define("RTL_ACIDENTE_RODOVIARIO", "Acidente Rodoviário");
define("RTL_QUEBRA_PROCEDIMENTO", "Quebra de procedimento");
define("RTL_RECUPERADO_VEICULO", "Recuperado");
define("RTL_DATA_HORA", "Data/Hora");
define("RTL_ADICIONAR_FOTOS", "Adicionar fotos");

define("RTL_GSM", "GSM");
define("RTL_SATELITAL", "Satelital");
define("RTL_HIBRIDO", "Hibrido");
define("RTL_RADIO_FREQUENCIA", "Radio frequência");
define("RTL_SEM_TECNOLOGIA", "Sem tecnologia");

define("RTL_AMARELA", "Amarela");
define("RTL_AZUL", "Azul");
define("RTL_BEGE", "Bege");
define("RTL_BRANCA", "Branca");
define("RTL_CINZA", "Cinza");
define("RTL_DOURADA", "Dourada");
define("RTL_FANTASIA", "Fantasia");
define("RTL_LARANJA", "Laranja");
define("RTL_MARROM", "Marrom");
define("RTL_PRATA", "Prata");
define("RTL_PRETA", "Preta");
define("RTL_ROSA", "Rosa");
define("RTL_ROXA", "Roxa");
define("RTL_VERDE", "Verde");
define("RTL_VERMELHA", "Vermelha");

define("RTL_GRANEL", "Granel");
define("RTL_BAU_SECO", "Baú seco");
define("RTL_BAU_FRIGORIFICADO", "Baú frigorificado");
define("RTL_CEGONHA", "Cegonha");
define("RTL_SIDER", "Sider");
define("RTL_CACAMBA", "Cacamba");
define("RTL_TANQUE", "Tanque");
define("RTL_CONTAINER", "Container");
define("RTL_OUTROS", "Outros");
define("RTL_VEICULO_RECUPERADO", "Veículo Recuperado?");
define("ROTULO_CAVALO_PLACA", "Placa");
define("RTL_INFORMACOES_GERAIS_ROUBO", "Informações gerais do roubo");
define("RTL_ULTIMAS_POSICOES", "Últimas posições enviadas");

define("TXT_ARQUIVO_INVALIDO", "Arquivo inválido");
define("TXT_CONFIRME_FINALIZAR_ROUBO", "Deseja realmente finalizar esse roubo? <br/>A ação não pode ser desfeita.");
define("TXT_CONFIRME_SALVAR_ROUBO", "Deseja salvar as informações do roubo?");
define("TXT_EXTENSAO_INVALIDA", "Extensão do arquivo não permitida.");
define("TXT_FINALIZAR_ROUBO_INVALIDO", "Você não pode finalizar um roubo que ainda não foi criado. Salve o roubo antes de finalizá-lo.");
define("TXT_FINALIZAR_ROUBO_FINALIZADO", "Esse roubo já foi finalizado.");
define("TXT_INFORMACOES_TEMPORARIAS", "Informações temporariamente salvas.<br/>Clique em Salvar na tela de roubo para guardar todas modificações.");
define("TXT_POPOVER_DATA_HORA_RECUPERADO", "Data/hora que o veículo foi recuperado");
define("TXT_POPOVER_NOME_OFICIAL", "Nome do oficial que atendeu a ocorrência");
define("TXT_POPOVER_TELEFONE_INFORMANTE", "Nome do informante do roubo");
define("TXT_POPOVER_TELEFONE_OFICIAL", "Telefone do oficial que atendeu a ocorrência");
define("TXT_POPOVER_TIPO_CARGA", "Tipo da carga do veículo");
define("TXT_SELECIONE_SITUACAO", "Por favor, selecione a situação do roubo antes de salvar.");
define("TXT_VALIDACAO_ROUBO_FINALIZADO", "Você não pode alterar roubos já finalizados.");
define("TXT_SALVE_ROUBO_CHAMADO", "Você precisa criar o roubo antes de abrir um chamado para o mesmo.");
define("TXT_SALVE_ROUBO_FOTO", "Você precisa criar o roubo antes de adicionar fotos a ele.");
define("TXT_SUCESSO_ANEXAR_ARQUIVOS", "Sucesso ao anexar os arquivos.");
