<?php
define("RTL_NOME", "Nome");
define("RTL_REPORTAR_ID_ACAO", "Reportar id de outra ação");
define("RTL_ESTADOS_ENTRADAS", "Estado das entradas: ");
define("RTL_ESTADOS_SAIDAS", "Estado das saídas: ");
define("RTL_ESTADO_ACELEROMETRO", "Estado do acelerômetro: ");
define("RTL_ESTADO_MODULO", "Estado do módulo: ");
define("RTL_MOTORISTA", "Motorista: ");
define("RTL_REPETICOES", "Repetir a verificação");
define("RTL_CONTROLE_HORARIO", "Horário de funcionamento");
define("RTL_HORIMETRO", "Se o horímetro for maior que...");
define("RTL_HODOMETRO", "Se o hodômetro for maior que...");
define("RTL_MACRO", "Macro");
define("RTL_CONTROLE_TELEMETRIA", "Controle de Telemetria: ");
define("RTL_MODIFICAR_ACAO_EMBARCADA", "Modificar Ação Embarcada");
define("TXT_ADICIONE_ACOES", "Adicione pelo menos uma ação para salvar");
define("RTL_ACAO_NUMERO", "Ação número");
define("RTL_ACOES", "Ações");
define("RTL_PORTAS", "Portas");
define("RTL_OUTROS", "Outros");
define("RTL_VERIFICAR", "Verificar");
define("RTL_CONDICAO", "Condição");
define("RTL_INFORMACOES_GERAIS", "Informações gerais");
define("RTL_SELECIONE", "-- SELECIONE --");
define("RTL_EDITAR_ACOES", "Editar ações");
define("RTL_SELECIONE_AGRUPAMENTO_VINCULADO", "Selecione o agrupamento de pontos (vinculados à ação)");
define("RTL_MACRO_EXECUTADA", "Macro executada");
define("RTL_SELECIONE_TELA_MACRO", "Selecione a tela de macro que executará essa ação");
define("RTL_MOSTRAR_TELA", "Mostrar uma tela de macro");
define("RTL_SELECIONE_TELA_MACRO_MENSAGEM", "Selecione a tela de macro que será mostrada");

define("RTL_ESTADO_ENTRADA", "Estado da entrada");
define("RTL_ESTADO_SAIDA", "Estado da saída");

define("RTL_DESATIVAR_SEGURANCA_SAIDA", "Desativar segurança da saída");
define("RTL_ATIVAR_SEGURANCA_SAIDA", "Ativar segurança da saída");
define("RTL_DESATIVAR_SEGURANCA_ENTRADA", "Desativar segurança da entrada");
define("RTL_ATIVAR_SEGURANCA_ENTRADA", "Ativar segurança da entrada");
define("RTL_DESATIVAR_SAIDA", "Desativar saída");
define("RTL_ATIVAR_SAIDA", "Ativar saída");
define("RTL_ACAO_CLIENTE", "Ação do cliente");
define("RTL_ACOES_AREA", "Ações da área do cliente");
define("RTL_ALARME", "Alarme");
define("RTL_ALARME_LIGADO", "Alarme ligado");
define("RTL_ALIMENTACAO", "Alimentação");
define("RTL_ALTA_TEMPERATURA", "Alta temperatura");
define("RTL_ALTERACAO_STATUS", "Alteração do status: ");
define("RTL_ANCORA", "Mudar raio da âncora");
define("RTL_ARQUIVO_AUDIO", "Arquivo de áudio");
define("RTL_ATUACAO_SAIDAS", "Atuação de saídas: ");
define("RTL_BANGUELA", "Banguela");
define("RTL_BATERIA_EXTERNA", "Bateria externa");
define("RTL_BATERIA_INTERNA", "Bateria interna");
define("RTL_CAIXA_MARCHA_ALTA", "Caixa marcha alta");
define("RTL_COACAO", "Utilizando senha e coação?");
define("RTL_CONTROLE_VELOCIDADE", "Controle de velocidade: ");
define("RTL_DELTA_TELEMETRIA", "Delta da telemetria");
define("RTL_DIRT_ROAD", "Está em estrada de chão?");
define("RTL_EM_OPERACAO", "Está em operação?");
define("RTL_MODO_OPERACAO", "Modo de operação");
define("RTL_ENTRADA_1", "Entrada 1");
define("RTL_ENTRADA_2", "Entrada 2");
define("RTL_ENTRADA_3", "Entrada 3");
define("RTL_ENTRADA_4", "Entrada 4");
define("RTL_ENTRADA_5", "Entrada 5");
define("RTL_ENTRADA_6", "Entrada 6");
define("RTL_ENTRADA_7", "Entrada 7");
define("RTL_ENTRADA_8", "Entrada 8");
define("RTL_ENVIO_POSICAO_ATUAL", "Envio de posição atual");
define("RTL_ENVIO_POSICOES_BLACKBOX", "Enviar posições de caixa preta");
define("RTL_EXCESSO_EMBREAGEM", "Excesso de embreagem");
define("RTL_EXCESSO_MARCHA_LENTA", "Excesso de marcha lenta");
define("RTL_EXCESSO_ROTACAO", "Excesso de rotação");
define("RTL_EXCESSO_VELOCIDADE", "Excedeu velocidade máxima configurada?");
define("RTL_EXECUTAR_TODAS_ACOES", "Executar todas as ações");
define("RTL_FALHA_PRESSAO_OLEO", "Falha na pressão do óleo");
define("RTL_FREIO_MOTOR_ACIONADO", "Freio motor acionado");
define("RTL_GPRS", "GPRS");
define("RTL_GPS", "GPS");
define("RTL_IGNICAO_LIGADA_SEM_GIRO", "Ignição ligada sem giro");
define("RTL_INTERVALO_GPRS_IGN_OFF", "Intervalo GPRS com ignição desligada");
define("RTL_INTERVALO_GPRS_IGN_ON", "Intervalo GPRS com ignição ligada");
define("RTL_INTERVALO_SAT_IGN_OFF", "Intervalo satelital com ignição desligada");
define("RTL_INTERVALO_SAT_IGN_ON", "Intervalo satelital com ignição ligada");
define("RTL_INTERVALO_TRANSMISSAO", "Intervalos de transmissão: ");
define("RTL_JAMMING", "Jamming");
define("RTL_LIGAR_NUMERO_CONFIGURADO", "Ligar para o número configurado");
define("RTL_LOGIN", "Houve login?");
define("RTL_LOGOFF", "Houve logoff?");
define("RTL_LOGOFF_MOTORISTA", "Deslogar motorista");
define("RTL_MENSAGEM_MOTORISTA", "Mensagem para o motorista");
define("RTL_MODO_SLEEP", "Está em modo sleep?");
define("RTL_MOTORISTA_GERENTE_LOGADO", "Motorista gerente executou o login?");
define("RTL_MOTORISTA_MANOBRISTA_LOGADO", "Motorista manobrista executou o login?");
define("RTL_MOTOR_FUNCIONANDO", "Motor funcionando");
define("RTL_MOVIMENTANDO", "Está movimentando?");
define("RTL_NAO_LOGADO", "Nenhum motorista logado");
define("RTL_PANICO", "Acionar pânico");
define("RTL_PARABRISA_LIGADO", "Parabrisa ligado");
define("RTL_PERIMETRO_URBANO", "Perímetro urbano");
define("RTL_PERIMETRO_URBANO_CHOVENDO", "Perímetro urbano chovendo");
define("RTL_PITCHING", "Pitching");
define("RTL_RODOVIA", "Rodovia");
define("RTL_RODOVIA_CHOVENDO", "Rodovia chovendo");
define("RTL_ROLLING", "Rolling");
define("RTL_SAIDA", "Saída");
define("RTL_SAIDA_1", "Saída 1");
define("RTL_SAIDA_2", "Saída 2");
define("RTL_SAIDA_3", "Saída 3");
define("RTL_SAIDA_4", "Saída 4");
define("RTL_SAIDA_5", "Saída 5");
define("RTL_SAIDA_6", "Saída 6");
define("RTL_SAIDA_7", "Saída 7");
define("RTL_SAIDA_8", "Saída 8");
define("RTL_SAIDA_ATIVADA", "Saída ativada");
define("RTL_SATELITAL", "Satelital");
define("RTL_SEGURANCA_ENTRADAS", "Segurança das entradas: ");
define("RTL_SEGURANCA_SAIDAS", "Segurança das saídas: ");
define("RTL_TELA_MACRO", "Tela macro");
define("RTL_TEMPO_PARADO", "Excedeu tempo parado configurado?");
define("RTL_TENSAO_ALTERNADOR", "Tensão do alternador");
define("RTL_TIPO_RODOVIA", "Tipo da rodovia");
define("RTL_VEICULO_EM_OPERACAO", "Veículo em operação");
define("RTL_ZERAR_CONTADOR_ACOES", "Zerar contador de ações");

define("RTL_ACIMA_VELOCIDADE_CONFIGURADA", "Acima da velocidade configurada");
define("RTL_ACIONA_PANICO", "Aciona pânico");
define("RTL_ALIMENTACAO_OK", "Alimentação OK");
define("RTL_ALTA_TENSAO", "Alta tensão");
define("RTL_ALTERA", "Altera");
define("RTL_ALTERAR_MODO_RODOVIARIO", "Alterar para modo rodoviário");
define("RTL_ALTERAR_MODO_URBANO", "Alterar para modo urbano");
define("RTL_ANALISA_ENTRAR_SLEEP", "Analisa entrar em modo sleep");
define("RTL_ARMAZENA_POSICAO", "Armazena a posição");
define("RTL_ATIVAR_ANCORA", "Ativar a âncora");
define("RTL_ATIVA_ANALISES_CLIENTE", "Ativa análise de ações do cliente");
define("RTL_ATIVA_MODO_SEGURANCA", "Ativa modo de segurança");
define("RTL_BAIXA_TENSAO", "Baixa tensão");
define("RTL_CARREGADA", "Carregada?");
define("RTL_CICLOS", "Ciclos");
define("RTL_CONECTADO", "Conectado");
define("RTL_DESATIVA_ANALISES_CLIENTE", "Desativa análises de ações do cliente");
define("RTL_DESATIVA_MODO_SEGURANCA", "Desativa modo de segurança");
define("RTL_DESCONECTADO", "Desconectado");
define("RTL_EFETUA", "Efetua");
define("RTL_EM_OPERACAO", "Em operação");
define("RTL_EM_USO", "É a fonte de alimentação atual?");
define("RTL_ENCERRA", "Encerra");
define("RTL_ENTRADA_ATIVADA_OBRIGATORIO", "Entrada ativada (obrigatório)");
define("RTL_ENTRADA_ATIVADA_OPCIONAL", "Entrada ativada (opcional)");
define("RTL_ENTRADA_DESATIVADA_OBRIGATORIO", "Entrada desativada (obrigatório)");
define("RTL_ENTRADA_DESATIVADA_OPCIONAL", "Entrada opcional (opcional)");
define("RTL_ENTRAR_ALARME", "Entrar em estado de alarme");
define("RTL_ENTRAR_OPERACAO", "Entrar em operação");
define("RTL_ENTROU_ALARME", "Entrou em estado de alarme?");
define("RTL_ENVIAR_POSICOES", "Enviar posições");
define("RTL_ESTA_ALARME", "Está em estado de alarme?");
define("RTL_EXECUTAR_TODAS_ACOES", "Executar todas as ações");
define("RTL_FALHA", "Houve falha?");
define("RTL_FALHA_COMUNICACAO_SATELITAL", "Falha na comunicação satelital");
define("RTL_FALHA_SINAL", "Falha sinal");
define("RTL_FIM_OPERACAO", "Finalizou operação?");
define("RTL_FORCAR_CALLBACK", "Forçar callback");
define("RTL_FORCAR_ENVIO", "Forçar envio");
define("RTL_FORCAR_SATELITAL", "Forçar satelital");
define("RTL_GPS_INVALIDO", "GPS inválido");
define("RTL_GPS_VALIDO", "GPS válido");
define("RTL_HODOMETRO_HECTOMETRO", "Hodômetro (centenas de metros)");
define("RTL_HORARIO_MAXIMA", "Horário máximo");
define("RTL_HORARIO_MINIMO", "Horário minimo");
define("RTL_HORIMETRO_MINUTOS", "Horímetro (minutos)");
define("RTL_HOUVE_ALTERACAO_ESTADO_OBRIGATORIO", "Houve alteração de estado (obrigatório)");
define("RTL_HOUVE_ALTERACAO_ESTADO_OPCIONAL", "Houve alteração de estado (opcional)");
define("RTL_ID_MOTORISTA_EMBARCADO", "ID do motorista embarcado");
define("RTL_INICIA", "Inicia");
define("RTL_INICIO_OPERACAO", "Iniciou a operação?");
define("RTL_INTERVALO_GPRS_IGN_OFF", "Intervalo GPRS com ignição desligada");
define("RTL_INTERVALO_GPRS_IGN_ON", "Intervalo GPRS com ignição ligada");
define("RTL_INTERVALO_SAT_IGN_OFF", "Intervalo satelital com ignição desligada");
define("RTL_INTERVALO_SAT_IGN_ON", "Intervalo satelital com ignição ligada");
define("RTL_LIMITE_RODOVIA", "Limite na rodovia");
define("RTL_LIMITE_RODOVIA_CHUVA", "Limite na rodovia com chuva");
define("RTL_LIMITE_URBANO", "Limite urbano");
define("RTL_LIMITE_URBANO_CHUVA", "Limite urbano com chuva");
define("RTL_MACRO", "Macro");
define("RTL_MENSAGEM", "Mensagem");
define("RTL_NAO_ALTERA", "Não altera");
define("RTL_NAO_EFETUA", "Não efetua");
define("RTL_NAO_FORCAR", "Não forçar");
define("RTL_NAO_VERIFICA", "Não verifica");
define("RTL_PLACEHOLDER_REPETICOES", "Quantas vezes a verificação deve ser verdadeira?");
define("RTL_PRESENCA_JAMMING", "Presença de jamming");
define("RTL_PRIMEIRO_ESTADO", "Primeiro estado (binário)");
define("RTL_RECARREGANDO", "Recarregando");
define("RTL_REINICIA", "Reinicia");
define("RTL_RESERVADO", "Reservado");
define("RTL_SAIDA_JAMMING", "Saída de jamming");
define("RTL_SAIR_ALARME", "Sair do estado de alarme");
define("RTL_SAIR_OPERACAO", "Sair de operação");
define("RTL_SAIU_ALARME", "Saiu do estado de alarme?");
define("RTL_SEM_SINAL_SATELITAL", "Sem sinal satelital");
define("RTL_TELA_MACRO", "Tela de macro");
define("RTL_TEMPO", "Tempo");
define("RTL_TEMPO_INVERSO", "Tempo inverso");
define("RTL_TEMPO_PARADO_EXCEDIDO", "Tempo parado excedido");
define("RTL_TEMPO_VALIDADE", "Tempo de validade");
define("RTL_TRANSMISSAO_MODO_SATELLITAL", "Transmissão modo satelital");
define("RTL_VERIFICA", "Verifica");
define("RTL_VERIFICA_ALTERACAO_ESTADO", "Verifica alteração no estado");
define("RTL_VERIFICA_ATIVADA", "Verifica ativada");
define("RTL_VERIFICA_DENTRO", "Está dentro do raio?");
define("RTL_VERIFICA_DESATIVADA", "Verifica desativada");
define("RTL_VERIFICA_ENTRADA", "Entrou no raio?");
define("RTL_VERIFICA_RODOVIA", "É rodovia?");
define("RTL_VERIFICA_SAIDA", "Saiu do raio?");
define("RTL_VERIFICA_URBANO", "É urbano?");
define("RTL_ZERAR_CONTADOR", "Zerar contador");
define("RTL_ATIVAR_ANCORA_RAIO_HECTOMETRO", "Raio de ativação da âncora (centenas de metros)");

define("RTL_VEICULO_ENQUANTO_DENTRO_AGRUPAMENTO", "Enquanto veículo estiver dentro de algum ponto");
define("RTL_VEICULO_ENTROU_AGRUPAMENTO", "Veículo entrou em qualquer ponto do agrupamento");
define("RTL_VEICULO_DEIXOU_AGRUPAMENTO", "Veículo saiu dos pontos do agrupamento");
define("RTL_VEICULO_FORA_AGRUPAMENTO", "Veículo está fora de qualquer ponto do agrupamento");
define("RTL_VEICULO_DENTRO_AGRUPAMENTO", "Veículo está dentro de algum ponto do agrupamento");
define("RTL_ID_SELECIONADO", "Id selecionado");
define("RTL_GRUPO_PONTO_INTERESSE", "Grupo de Ponto de Interesse Embarcado");
define("RTL_SELECIONE_MOTORISTA", "Selecione o motorista (id 0 = validar todos da biblioteca)");