<?
define("RTL_ID", "Id");
define("RTL_ID_VEICULO", "Id Veiculo");
define("RTL_ID_COMANDO_ENVIADO", "Id Comando Enviado");
define("RTL_DESCRICAO_LISTAGEM_ACOMPANHAMENTO_BLOQUEIO", "Listagem de Acompanhamento Bloqueio");
define("TXT_ALERT_SUCESSO_MODIFICAR", "Sucesso ao modificar registro");
define("TXT_ALERT_ERRO_OPERACAO", "Erro ao executar operação");
define("TXT_ALERT_SUCESSO_OPERACAO", "Sucesso ao executar operação");
define("TXT_ALERT_SUCESSO_ADICIONAR", "Sucesso ao Adicionar registro");
define("TXT_CONFIRME_DELETE_REGISTROS", "Deseja realmente remover este(s) registro(s)?");
define("TXT_CONFIRMACAO_DELETE_REGISTROS", "Registros foram excluidos com exito");
define("TXT_ERRO_DELETAR_REGISTROS", "Erro ao Excluir registros");
define("TXT_ERRO_NENHUM_REGISTRO_SELECIONADO", "Por favor, selecione itens para serem excluidos");
define("TXT_ATENCAO", "Atenção");
define("TXT_PREENCHA_CAMPOS_OBRIGATORIOS", "Por favor preencher todos os campos obrigatórios");
define("RTL_ACOMPANHAMENTO_BLOQUEIO", "Acompanhamento Bloqueio");
define("RTL_MODIFICAR_ACOMPANHAMENTO_BLOQUEIO", "Modificar Acompanhamento Bloqueio");
define("RTL_ADICIONAR_ACOMPANHAMENTO_BLOQUEIO", "Adicionar Acompanhamento Bloqueio");
define("RTL_ROTULO", "Placa");
define("RTL_BLOQUEIO", "Bloqueio");
define("RTL_IGNICAO", "Ignição");
define("RTL_DATA_HORA_ULTIMA_POSICAO", "Data/Hora última posição");
define("RTL_STATUS_COMANDO", "Status do comando");
define("RTL_ACOES", "Ações");
define("RTL_PLACEHOLDER_BUSCA_VEICULO", "Selecione os veículos para acompanhamento");
define("RTL_BLOQUEAR", "Bloquear");
define("RTL_DESBLOQUEAR", "Desbloquear");
define("RTL_VISUALIZAR_NO_MAPA", "Visualizar no mapa");
define("RTL_INFO", "Info");
define("RTL_COMANDOS_ENVIADOS", "Comandos Enviados");
define("RTL_BLOQUEADO", "Bloqueado");
define("RTL_DESBLOQUEADO", "Desbloqueado");
define("RTL_LIGADO", "Ligado");
define("RTL_DESLIGADO", "Desligado");
define("RTL_ENVIAR_COMANDO_DESBLOQUEIO", "Deseja enviar o comando de desbloqueio?");
define("RTL_ENVIAR_COMANDO_BLOQUEIO", "Deseja enviar o comando de bloqueio?");
define("RTL_VELOCIDADE", "Velocidade");
define("RTL_LOGRADOURO", "Logradouro");
define("RTL_FILTRAR_STATUS", "Filtrar status");
define("RTL_COMPLEMENTO", "Complemento");

define("TXT_ALERTA_ENVIO_BLOQUEIO", "Será enviado comandos de bloqueio para TODOS os veículos adicionados.<br/>Tenha certeza dos veículos antes de salvar.");
define("TXT_DESABILITAR_JANELA_CONFIRMACAO", "Desabilitar janela de confirmação?");