<?
define("RTL_ID", "Id");
define("RTL_ID_GRUPO", "Id Grupo");
define("RTL_NOME", "Nome");
define("RTL_DATA_HORA_CADASTRO", "Data Hora Cadastro");
define("RTL_DESCRICAO_LISTAGEM_APP_QUESTIONARIO", "Listagem de App Questionario");
define("TXT_ALERT_SUCESSO_MODIFICAR", "Sucesso ao modificar registro");
define("TXT_ALERT_ERRO_OPERACAO", "Erro ao executar operação");
define("TXT_ALERT_SUCESSO_OPERACAO", "Sucesso ao executar operação");
define("TXT_ALERT_SUCESSO_ADICIONAR", "Sucesso ao Adicionar registro");
define("TXT_CONFIRME_DELETE_REGISTROS", "Deseja realmente remover este(s) registro(s)?");
define("TXT_CONFIRMACAO_DELETE_REGISTROS", "Registros foram excluidos com exito");
define("TXT_ERRO_DELETAR_REGISTROS", "Erro ao Excluir registros");
define("TXT_ERRO_NENHUM_REGISTRO_SELECIONADO", "Por favor, selecione itens para serem excluidos");
define("TXT_ATENCAO", "Atenção");
define("TXT_PREENCHA_CAMPOS_OBRIGATORIOS", "Por favor preencher todos os campos obrigatórios");
define("RTL_APP_QUESTIONARIO", "Questionários");
define("RTL_MODIFICAR_APP_QUESTIONARIO", "Modificar App Questionario");
define("RTL_ADICIONAR_APP_QUESTIONARIO", "Adicionar App Questionario");
define("RTL_QUESTOES", "Questões");
define("RTL_PLACEHOLDER_BUSCAR_QUESTOES", "Digite algo para buscar questões");
define("RTL_APLICAR_PESQUISA", "Aplicar pesquisa");
define("RTL_QUESTIONARIO", "Questionário");
define("RTL_APLICAR_PARA", "Aplicar para");