<?
define("RTL_ID", "Id");
define("RTL_XML", "Xml");
define("RTL_NOME", "Nome");
define("RTL_EXCLUIDO", "Excluido");
define("RTL_DESCRICAO_LISTAGEM_BIBLIOTECA_PONTO_INTERESSE", "Listagem de Biblioteca Ponto Interesse");
define("TXT_ALERT_SUCESSO_MODIFICAR", "Sucesso ao modificar registro");
define("TXT_ALERT_ERRO_OPERACAO", "Erro ao executar operação");
define("TXT_ALERT_SUCESSO_OPERACAO", "Sucesso ao executar operação");
define("TXT_ALERT_SUCESSO_ADICIONAR", "Sucesso ao Adicionar registro");
define("TXT_CONFIRME_DELETE_REGISTROS", "Deseja realmente remover este(s) registro(s)?");
define("TXT_CONFIRMACAO_DELETE_REGISTROS", "Registros foram excluidos com exito");
define("TXT_ERRO_DELETAR_REGISTROS", "Erro ao Excluir registros");
define("TXT_ERRO_NENHUM_REGISTRO_SELECIONADO", "Por favor, selecione itens para serem excluidos");
define("TXT_ATENCAO", "Atenção");
define("TXT_PREENCHA_CAMPOS_OBRIGATORIOS", "Por favor preencher todos os campos obrigatórios");
define("RTL_BIBLIOTECA_PONTO_INTERESSE", "Biblioteca Ponto Interesse");
define("RTL_ADICIONAR_BIBLIOTECA_PONTO_INTERESSE", "Adicionar Biblioteca Ponto Interesse");
define("RTL_MODIFICAR_BIBLIOTECA_PONTO_INTERESSE", "Modificar Biblioteca Ponto Interesse");
define("RTL_ADICIONAR_PONTO_INTERESSE", "Adicionar ponto de interesse");
define("RTL_MODIFICAR_PONTO_INTERESSE", "Modificar ponto de interesse");
define("RTL_VINCULAR_PONTO_INTERESSE", "Vincular ponto de interesse");
define("RTL_PLACEHOLDER_BUSCA_PONTO_INTERESSE", "Busque pontos de interesse pelo nome");
define("RTL_VINCULAR_PONTOS", "Vincular ponto de interesse");
define("RTL_EDITAR_GRUPOS", "Editar grupos");
define("RTL_MODIFICAR_BIBLIOTECA_PONTO_INTERESSE_GRUPOS", "Modificar Grupo de pontos");
define("RTL_ADICIONAR_BIBLIOTECA_PONTO_INTERESSE_GRUPOS", "Adicionar Grupo de pontos");
