<?
define("RTL_ID", "Id");
define("RTL_ID_MOTORISTA", "Id Motorista");
define("RTL_ID_BIBLIOTECA_MOTORISTA_EMBARCADO", "Id Biblioteca Motorista Embarcado");
define("RTL_LOGIN", "Login");
define("RTL_SENHA", "Senha");
define("RTL_DONGLE", "Dongle");
define("RTL_DESCRICAO_LISTAGEM_BIBLIOTECA_MOTORISTA_EMBARCADO_MOTORISTAS", "Listagem de Biblioteca Motorista Embarcado Motoristas");
define("TXT_ALERT_SUCESSO_MODIFICAR", "Sucesso ao modificar registro");
define("TXT_ALERT_ERRO_OPERACAO", "Erro ao executar operação");
define("TXT_ALERT_SUCESSO_OPERACAO", "Sucesso ao executar operação");
define("TXT_ALERT_SUCESSO_ADICIONAR", "Sucesso ao Adicionar registro");
define("TXT_CONFIRME_DELETE_REGISTROS", "Deseja realmente remover este(s) registro(s)?");
define("TXT_CONFIRMACAO_DELETE_REGISTROS", "Registros foram excluidos com exito");
define("TXT_ERRO_DELETAR_REGISTROS", "Erro ao Excluir registros");
define("TXT_ERRO_NENHUM_REGISTRO_SELECIONADO", "Por favor, selecione itens para serem excluidos");
define("TXT_ATENCAO", "Atenção");
define("TXT_PREENCHA_CAMPOS_OBRIGATORIOS", "Por favor preencher todos os campos obrigatórios");
define("RTL_BIBLIOTECA_MOTORISTA_EMBARCADO_MOTORISTAS", "Biblioteca Motorista Embarcado Motoristas");
define("RTL_MODIFICAR_BIBLIOTECA_MOTORISTA_EMBARCADO_MOTORISTAS", "Modificar Biblioteca Motorista Embarcado Motoristas");
define("RTL_ADICIONAR_BIBLIOTECA_MOTORISTA_EMBARCADO_MOTORISTAS", "Adicionar Biblioteca Motorista Embarcado Motoristas");
