<?
define("RTL_ABRIR_CERCA_POLIGONO", "Abrir Cerca Polígono");
define("RTL_ADICIONAR_CERCA_POLIGONO", "Adicionar Cerca Polígono");
define("RTL_CERCA", "Cerca");
define("RTL_CERCA_POLIGONO", "Cerca Polígono");
define("RTL_CHECKBOX_EXCLUIR", "Caixa de seleção");
define("RTL_DATA_HORA_CADASTRO", "Data/Hora Cadastro");
define("RTL_DATA_HORA_GRAVACAO", "Data/Hora Gravação");
define("RTL_EVENTO", "Evento");
define("RTL_GERAR", "Gerar");
define("RTL_ID", "Id");
define("RTL_LISTAGEM_CERCA_POLIGONO", "Listagem de Cerca Polígono");
define("RTL_LOGRADOURO_REFERENCIA", "Logradouro de Referência");
define("RTL_MODIFICAR_CERCA_POLIGONO", "Modificar Cerca Polígono");
define("RTL_NOME", "Nome");
define("RTL_OBSERVACAO", "Observação");
define("RTL_VEICULOS_CERCAS", "Veículos x Cerca");
define("RTL_VEICULOS_VINCULADOS", "Veículos Vinculados");
define("RTL_VELOCIDADE", "Velocidade");
define("RTL_VELOCIDADE_ATINGIDA", "Velocidade Atingida");
define("RTL_VISUALIZAR_CERCA", "Visualizar Cerca");
define("RTL_PERMITIR_EVENTO", "Permitir eventos de velocidade");
define("RTL_LIMITE", "Limite");
define("RTL_VER_NO_MAPA", "Ver no mapa");
define("RTL_BTN_LIMPAR", "Limpar");
define("RTL_REGRAS_AGENDAMENTO", "Regras de Agendamento");
define("RTL_PDF", "PDF");
define("RTL_PLACEHOLDER_BUSCA_GRUPO", "Busque grupos que visualizarão a cerca");

define("TXT_PREENCHA_CAMPOS_OBRIGATORIOS", "Preencha todos os campos obrigatórios antes de salvar o formulário.");
define("TXT_SUCESSO_VINCULAR_VEICULO", "Sucesso ao vincular os veículos.");
define("TXT_VERIFIQUE_POLIGONO", "O polígono deve ter pelo menos 3 pontos.");
define("RTL_GRAFICO_VEICULO_CERCA", "Gráfico de Veículos por Cerca");
define("TXT_ERRO_REGISTRO_EXISTENTE", "Esse nome já existe");
define("TXT_TUTORIAL_ABA_GERAL", "Aba geral com informações resumidas e gráficos acerca das Cercas de Polígono.");
define("TXT_TUTORIAL_GRAFICO_VEICULO_CERCA", "Gráfico que mostra quantos veículos estão vinculados a cada cerca.");
define("TXT_TUTORIAL_LISTAGEM", "Aba que contém a listagem e cadastro de Cercas de Polígono.");
define("TXT_TUTORIAL_ADICIONAR", "Clique para adicionar Cercas de Polígono ao sistema.");
define("TXT_TUTORIAL_IMPRIMIR", "Gera uma listagem para impressão dos registros de Cerca Polígono, sem imagens.");
define("TXT_TUTORIAL_GERAR_PDF", "Gera um arquivo em PDF no browser que pode ser salvo no computador com a listagem de Cerca Polígono.");
define("TXT_TUTORIAL_BUSCA", "Digite o que procura e tecle enter ou clique na lupa para pesquisar registros que possuam o texto procurado.");
define("TXT_TUTORIAL_GRID", "Listagem padrão com todas as informações das cercas e uma representação estática da mesma. A coluna da direita possui ações de modificar e vincular veículos à cerca.");
define("TXT_TUTORIAL_RELATORIO", "Relatório de eventos de Cerca Polígono.");
define("TXT_TUTORIAL_GRUPO", "Selecione um grupo para o qual deseja filtrar os resultados do relatório.");
define("TXT_TUTORIAL_VEICULO", "Selecione um veículo para o qual deseja filtrar os resultados do relatório.");
define("TXT_TUTORIAL_CERCA", "Selecione uma cerca para a qual deseja filtrar os resultados do relatório.");
define("TXT_TUTORIAL_DATA_HORA", "Selecione um intervalo de data e hora para filtrar os resultados do relatório.");
define("TXT_TUTORIAL_IMPRIMIR_RELATORIO", "Gera uma lista para impressão com os resultados dos filtros. Não é necessário gerar o relatório antes de gerar a impressão.");
define("TXT_TUTORIAL_PDF_RELATORIO", "Gera um arquivo em PDF com os resultados dos filtros. Não é necessário gerar o relatório antes de gerar o PDF.");
define("TXT_TUTORIAL_XML_RELATORIO", "Gera um arquivo XLS com download automatico e que pode ser aberto utilizando qualquer editor de planilhas.");
define("TXT_TUTORIAL_CONFIGURACOES_RELATORIO", "Selecione as colunas que deseja ver no relatório e personalize de acordo com suas preferências.");
define("TXT_TUTORIAL_BUSCA_TIPO", "Ao buscar por placas, serão pesquisados diretamente os veículos desejados. Já por grupos, digite o nome do grupo desejado e serão trazidos as placas vinculadas a grupos que correspondem a pesquisa.");
define("TXT_TUTORIAL_BUSCA", "Digite o texto procurado aqui e clique em buscar para consultar registros que correspondem a sua busca.");
define("TXT_TUTORIAL_DISPONIVEIS", "Os resultados da pesquisa irão aparecer aqui. Clique na seta '->' para adicionar todos aos selecionados, ou no '+' para adicionar individualmente.");
define("TXT_TUTORIAL_SELECIONADOS", "Listagem dos registros selecionados da lista da esquerda.");
define("TXT_TUTORIAL_LISTAGEM_SELECIONADOS", "Marque os eventos de entrada e saída para os veículos que desejar. Os eventos levarão um tempo para serem gerados a partir do momento em que os vínculos forem salvos.");
define("TXT_TUTORIAL_NOME", "Nome identificador da cerca.");
define("TXT_TUTORIAL_PERMITIR_EVENTO", "Se gostaria de limitar a velocidade dos veículos dentro dessa cerca, marque esse campo.");
define("TXT_TUTORIAL_LIMITE_VELOCIDADE", "Digite o limite de velocidade em KM/H para os eventos de velocidade dentro desta cerca.");
define("TXT_TUTORIAL_LOGRADOURO_REFERENCIA", "Procure um endereço para ter como base para a cerca polígono. Esse endereço serve apenas para facilitar a busca de locais no mapa e não será salvo no sistema.");
define("TXT_TUTORIAL_MAPA_CERCA_POLIGONO", "Clique no mapa e crie um polígono com pelo menos três vértices. Caso deseje remover um ponto, clique no marcador do ponto que deseja remover.");
define("TXT_MSG_BUSCA", "Colunas de Busca: Nome.");
