<?php
define("RTL_ADICIONAR_CERCA_ROTAS", "Adicionar Cerca Rotas");
define("RTL_CERCA", "Cerca");
define("RTL_CERCA_ROTAS", "Cerca Rotas");
define("RTL_CHECKBOX_EXCLUIR", "Caixa de seleção");
define("RTL_DATA_HORA_GRAVACAO", "Data/Hora Gravação");
define("RTL_ENDERECOS", "Endereços");
define("RTL_GERAR", "Gerar");
define("RTL_GERAR_ROTA", "Gerar Roteiro");
define("RTL_ID", "Id");
define("RTL_KML", "Importar KML");
define("RTL_LISTAGEM_CERCA_ROTAS", "Listagem de Cerca Rotas");
define("RTL_LOGRADOURO", "Logradouro");
define("RTL_LOGRADOURO_FINAL", "Ponto de chegada");
define("RTL_LOGRADOURO_INICIAL", "Ponto de partida");
define("RTL_MODIFICAR_CERCA_ROTAS", "Modificar Cerca Rotas");
define("RTL_NOME", "Nome");
define("RTL_OBSERVACAO", "Observação");
define("RTL_PONTOS_INTERESSE", "Pontos de Interesse");
define("RTL_REMOVER_PONTO_PASSAGEM", "Remover ponto de passagem");
define("RTL_VEICULOS_CERCAS", "Veículos x Cerca");
define("RTL_VEICULOS_VINCULADOS", "Veículos Vinculados");
define("RTL_VELOCIDADE", "Velocidade");
define("RTL_VELOCIDADE_ATINGIDA", "Velocidade Atingida");
define("RTL_GRAFICO_VEICULO_CERCA", "Gráfico de Veículos por Cerca");
define("RTL_ADICIONAR_PONTO_PASSAGEM", "Adicionar ponto de passagem");
define("RTL_PONTO_PASSAGEM", "Ponto de passagem");
define("RTL_VER_NO_MAPA", "Ver no mapa");
define("RTL_RAIO", "Raio");
define("RTL_PADRAO_RAIO", "50 metros (padrão)");
define("RTL_PDF", "PDF");
define("RTL_DISTANCIA_PONTO", "Distância do ponto anterior até aqui");
define("RTL_DISTANCIA_TOTAL", "Distância total");
define("RTL_LIMITE_VELOCIDADE", "Limite de velocidade");
define("TXT_PONTOS_DEMAIS", "Número excessivo de pontos no KML.");
define("RTL_PLACEHOLDER_BUSCA_GRUPO", "Busque grupos que visualizarão a cerca");
define("RTL_PLACEHOLDER_BUSCA_PONTO_INTERESSE", "Busque por pontos de interesse");

define("TXT_END_FIM_INICIO_BRANCO", "Os endereços inicial e final devem ser preenchidos");
define("TXT_ERRO_SERVIDOR", "A solicitação de rota não pôde ser processada devido a um erro no servidor.<br/>O pedido pode ter sucesso se você tentar novamente.");
define("TXT_EXCESSO_PONTOS", "A solicitação de rota não pôde ser processada devido ao numero de endereços requisitados.");
define("TXT_GERAR_ROTA", "Você precisa gerar a rota pelo menos uma vez");
define("TXT_KML_VAZIO", "Arquivo KML não pode estar em branco.");
define("TXT_MINIMO_PONTO_INTERESSE", "Selecione pelo menos 2 pontos de interesse para gerar a rota");
define("TXT_NUMERO_MAXIMO_PONTOS", "Número máximo de pontos atingido. A rota será gerada até o limite possível.");
define("TXT_OPERACAO_ERRO", "Erro ao executar operação.");
define("TXT_OPERACAO_SUCESSO", "Operação executada com sucesso.");
define("TXT_PONTO_INTERESSE_VAZIO", "Existem endereços vazios. Favor verificar seus pontos de interesse");
define("TXT_PONTOS_NAO_ENCONTRADOS", "Um ou mais pontos não podem ser encontrados.");
define("TXT_PREENCHA_CAMPOS_OBRIGATORIOS", "Preencha todos os campos obrigatórios antes de salvar o registro");
define("TXT_RAIO_INVALIDO", "O raio deve ser maior que 50");
define("TXT_REQUISICOES_MINUTO", "Limite de requisições por minuto excedida.<br/>Aguarde 60 segundos antes de fazer uma nova requisição.");
define("TXT_ROTA_SEM_RESULTADO", "A rota escolhida não retornou resultado.");
define("TXT_SERVICO_REQUISICAO_PERMISSAO", "A página da web não tem permissão para utilizar o serviço de direções.");
define("TXT_TUTORIAL_NOME", "Nome identificador da cerca.");
define("TXT_TUTORIAL_ENDERECOS", "Aba que contém os endereços dos pontos da rota.");
define("TXT_TUTORIAL_LOGRADOURO_INICIAL", "Ponto de partida da rota.");
define("TXT_TUTORIAL_ADICIONAR_PONTO_PASSAGEM", "Clique para adicionar um ponto de passagem por onde a rota deverá seguir.");
define("TXT_TUTORIAL_PONTO_PASSAGEM", "Digite aqui o endereço do ponto desejado. Caso não queira mais esse ponto de passagem, clique no '-' vermelho para removê-lo.");
define("TXT_TUTORIAL_LOGRADOURO_FINAL", "Ponto final da rota.");
define("TXT_TUTORIAL_GERAR_ROTEIRO", "Clique para gerar a rota e vê-la no mapa. É necessário gerar a rota pelo menos uma vez antes de salvar.");
define("TXT_TUTORIAL_KML", "Importação de arquivos .kml");
define("TXT_TUTORIAL_IMPORTAR_KML", "Importe arquivos de rota .kml e crie sua rota no sistema a partir dele. Apenas arquivos simples de rotas são suportados.");
define("TXT_TUTORIAL_PONTOS_INTERESSE", "Seleção de pontos de interesse");
define("TXT_TUTORIAL_SELECIONAR_PONTOS_INTERESSE", "Selecione aqui pontos de interesse para utilizar como pontos da rota.");
define("TXT_TUTORIAL_ABA_GERAL", "Aba geral com informações resumidas e gráficos acerca das Cercas de Rotas.");
define("TXT_TUTORIAL_GRAFICO_VEICULO_CERCA", "Gráfico que mostra quantos veículos estão vinculados a cada cerca.");
define("TXT_TUTORIAL_LISTAGEM", "Aba que contém a listagem e cadastro de Cercas de Rotas.");
define("TXT_TUTORIAL_ADICIONAR", "Clique para adicionar Cercas de Rotas ao sistema.");
define("TXT_TUTORIAL_IMPRIMIR", "Gera uma listagem para impressão dos registros de Cerca Rotas, sem imagens.");
define("TXT_TUTORIAL_GERAR_PDF", "Gera um arquivo em PDF com os resultados dos filtros. Não é necessário gerar o relatório antes de gerar o PDF.");
define("TXT_TUTORIAL_BUSCA", "Digite o que procura e tecle enter ou clique na lupa para pesquisar registros que possuam o texto procurado.");
define("TXT_TUTORIAL_GRID", "Listagem padrão com todas as informações das cercas. A coluna da direita possui ações de modificar e vincular veículos à cerca.");
define("TXT_TUTORIAL_RELATORIO", "Relatório de eventos de Cerca Rotas.");
define("TXT_TUTORIAL_GRUPO", "Selecione um grupo para o qual deseja filtrar os resultados do relatório.");
define("TXT_TUTORIAL_VEICULO", "Selecione um veículo para o qual deseja filtrar os resultados do relatório.");
define("TXT_TUTORIAL_CERCA", "Selecione uma cerca para a qual deseja filtrar os resultados do relatório.");
define("TXT_TUTORIAL_DATA_HORA", "Selecione um intervalo de data e hora para filtrar os resultados do relatório.");
define("TXT_TUTORIAL_IMPRIMIR_RELATORIO", "Gera uma lista para impressão com os resultados dos filtros. Não é necessário gerar o relatório antes de gerar a impressão.");
define("TXT_TUTORIAL_PDF_RELATORIO", "Gera um arquivo em PDF com os resultados dos filtros. Não é necessário gerar o relatório antes de gerar o PDF.");
define("TXT_TUTORIAL_XML_RELATORIO", "Gera um arquivo XLS com download automatico e que pode ser aberto utilizando qualquer editor de planilhas.");
define("TXT_TUTORIAL_CONFIGURACOES_RELATORIO", "Selecione as colunas que deseja ver no relatório e personalize de acordo com suas preferências.");
define("TXT_TUTORIAL_BUSCA_TIPO", "Ao buscar por placas, serão pesquisados diretamente os veículos desejados. Já por grupos, digite o nome do grupo desejado e serão trazidos as placas vinculadas a grupos que correspondem a pesquisa.");
define("TXT_TUTORIAL_BUSCA", "Digite o texto procurado aqui e clique em buscar para consultar registros que correspondem a sua busca.");
define("TXT_TUTORIAL_DISPONIVEIS", "Os resultados da pesquisa irão aparecer aqui. Clique na seta '->' para adicionar todos aos selecionados, ou no '+' para adicionar individualmente.");
define("TXT_TUTORIAL_SELECIONADOS", "Listagem dos registros selecionados da lista da esquerda.");
define("TXT_TUTORIAL_LISTAGEM_SELECIONADOS", "Marque os eventos de entrada e saída para os veículos que desejar. Os eventos levarão um tempo para serem gerados a partir do momento em que os vínculos forem salvos.");
define("TXT_MSG_BUSCA", "Colunas de Busca: Nome.");
define("RTL_EVENTO", "Evento");