<?php
define("RTL_CONTROLE_COLABORADOR", "Controle Colaborador");
define("RTL_ADICIONAR_COLABORADOR", "Adicionar Colaborador");
define("RTL_MODIFICAR_COLABORADOR", "Modificar Colaborador");
define("RTL_ADICIONAR_JUSTIFICATIVA", "Adicionar Justificativa");
define("RTL_DADOS", "Dados");
define("RTL_CARGA_HORARIA", "Carga Horária");
define("RTL_NOME", "Nome");
define("TXT_ERRO_DATA_ADM", "Data de admissão preenchimento obrigatório");
define("ROTULO_DATA_ADMISSAO", "Data de admissão");
define("ROTULO_DATA_DEMISSAO", "Data de demissão");
define("RTL_INATIVO", "Inativo");
define("TXT_ERRO_DATA_INICIO", "Inicio de férias preenchimento obrigatório");
define("TXT_ERRO_DATA_FIM", "Fim de férias preenchimento obrigatório");
define("TXT_ERRO_CARTAO", "Número Cartão preenchimento obrigatório");
define("TXT_ERRO_INTERVALO_DATA", "Intervalo de datas é inválido");
define("TXT_ERRO_INTERVALO_FERIAS", "Férias não pode estar ativo no periodo escolhido");
define("TXT_MSG_BUSCA", "Colunas de Busca: Nome, CPF, Número do Cartão");
define("RTL_FOTO", "Foto");
define("RTL_REMOVER_FOTO", "Remover foto");
define("TXT_CONFIRMAR_REMOCAO_FOTO", "Deseja realmente remover a foto desse colaborador?");
define("TXT_FORMATO_FOTO_INVALIDO", "Formato da foto inválido");
define("RTL_JORNADA_DIAS_SEMANA", "Jornada de trabalho (dias da semana)");
define("RTL_JORNADA_FIM_SEMANA", "Jornada de trabalho (fins de semana)");
define("TXT_ERRO_COLABORADOR", "Selecione um colaborador");
define("TXT_ALERT_SUCESSO_MODIFICAR", "Sucesso ao modificar registro");
define("TXT_ALERT_SUCESSO_ADICIONAR", "Sucesso ao Adicionar registro");
define("TXT_COLABORADOR_CARTAO_REPETIDO", "Esse Número de cartão já está cadastrado.");
define("TXT_COLABORADOR_CPF_REPETIDO", "Esse CPF já está cadastrado.");
define("RTL_EXCLUIR_FERIAS", "Excluir férias");
define("RTL_INICIO_FERIAS", "Inicio férias");
define("RTL_FIM_FERIAS", "Fim férias");
define("RTL_INICIO_JORNADA", "Início Jornada");
define("RTL_INICIO_INTERVALO", "Início Intervalo");
define("RTL_FIM_INTERVALO", "Fim Intervalo");
define("RTL_FIM_JORNADA", "Fim Jornada");
define("TXT_ERRO_REL_VISUALIZACAO", "Relatório por grupo disponível somente sintético");
define("TXT_ERRO_COLABORADOR_GRUPO", "Selecione ao menos um colaborador/grupo");
define("TXT_ERRO_COLABORADOR", "Selecione um colaborador");
define("COPIAR_CARGA_COLABORADOR", "Copiar a carga de um colaborador");
define("RTL_TIPO_BATIDA", "Tipo de batida");
define("TXT_PREENCHA_CAMPOS_OBRIGATORIOS", "Por favor, preencha todos os campos obrigatórios.");
define("RTL_HORA", "Hora");
define("ROTULO_DATA", "Data");
define("RTL_LIMITE_BATIDA_DIA", "Horário limite de batida");
define("RTL_VIRADA_DO_DIA", "Horário de Virada do Dia");
define("RTL_ASSINATURA_COLABORADOR", "Assinatura do Colaborador");
define("RTL_ASSINATURA_RH", "Assinatura do RH");
define("RTL_INICIO_JORNADA_EXTRA", "Início Jornada Extra");
define("RTL_FIM_JORNADA_EXTRA", "Fim Jornada Extra");
define("RTL_INICIO_JORNADA_ADICIONAL", "Início Jornada Adicional");
define("RTL_FIM_JORNADA_ADICIONAL", "Fim Jornada Adicional");
define("RTL_INICIO", "Início");
define("RTL_FIM", "Fim");
define("RTL_INICIO_JORNADA_1", "Início Jornada 1");
define("RTL_FIM_JORNADA_1", "Fim Jornada 1");
define("RTL_INICIO_JORNADA_2", "Início Jornada 2");
define("RTL_FIM_JORNADA_2", "Fim Jornada 2");
define("RTL_INICIO_JORNADA_3", "Início Jornada 3");
define("RTL_FIM_JORNADA_3", "Fim Jornada 3");

//txt tutorial//
define("TXT_TUTORIAL_ESTATISTICAS", "Estatísticas dos colaboradores cadastrados");
define("TXT_TUTORIAL_LISTAGEM", "Listagem dos colaboradores cadastrados");
define("TXT_TUTORIAL_BTN", "Adicionar colaborador");
define("TXT_TUTORIAL_ADICIONAR", "Clique aqui para adicionar um novo colaborador");
define("TXT_TUTORIAL_DADOS", "Dados do colaborador");
define("TXT_TUTORIAL_PREENCHA", "Preencha os campos obrigatórios");
define("TXT_TUTORIAL_ATIVO", "Ativo");
define("TXT_TUTORIAL_ATIVO_DESC", "Identificador de atividade");
define("RTL_TUTORIAL_CARTAO", "Cartão ponto");
define("TXT_TUTORIAL_CARTAO", "Número do cartão ponto do colaborador");
define("TXT_TUTORIAL_NOME", "Nome do colaborador");
define("TXT_TUTORIAL_CPF", "CPF do colaborador");
define("TXT_TUTORIAL_ADMISSAO", "Data de contratação do colaborador");
define("TXT_TUTORIAL_CARGA", "Cadastre aqui a carga horária diária do colaborador");
define("TXT_TUTORIAL_RELATORIO", "Relatório de pontos dos colaboradores");
define("TXT_TUTORIAL_NOME_REL", "Nome do colaborador a ser pesquisado");
define("TXT_TUTORIAL_VISUALIZACAO", "Escolha o tipo de visualização. Sintético para um relatório simples e analítico para um relatório completo");

