<?
define("RTL_ICONE", "Ícone");
define("RTL_ROTULO", "Placa");
define("RTL_COMPLEMENTO", "Complemento");
define("RTL_LOGRADOURO", "Logradouro");
define("RTL_VELOCIDADE", "Vel (Km/h)");
define("RTL_ODOMETRO", "Hodômetro");
define("RTL_ORIGEM_DESTINO", "Origem/Destino");
define("RTL_OBSERVACAO", "Observação");
define("RTL_HORIMETRO", "Horímetro");
define("RTL_INFORMACOES", "Informações");
define("RTL_BLOQUEADO", "Bloqueado");
define("RTL_DESBLOQUEADO", "Desbloqueado");
define("RTL_LIGADO", "Ligado");
define("RTL_DESLIGADO", "Desligado");
define("RTL_EM_PANICO", "Em pânico");
define("RTL_NORMAL", "Normal");
define("RTL_DE", "De: ");
define("RTL_PARA", "Para: ");
define("RTL_FINALIZAR_PANICO", "Finalizar pânico");
define("RTL_IGNICAO", "Ignição");
define("RTL_LIGADA", "Ligada");
define("RTL_DESLIGADA", "Desligada");
define("RTL_PANICO", "Pânico");
define("RTL_COM_PANICO", "Com pânico");
define("RTL_SEM_PANICO", "Sem pânico");
define("RTL_BUSCAR", "Buscar");
define("RTL_MODELO_RASTREADOR", "Modelo");
define("RTL_TODAS", "Todas");
define("RTL_GERAR", "Gerar");
define("RTL_ULTIMA_POSICAO", "Última posição desde");
define("RTL_MONITORAR_VEICULO", "Monitorar veículo");
define("RTL_INFORMACAO_DO_VEICULO", "Informações do veículo");
define("RTL_MODIFICAR_VEICULO", "Modificar veículo");
define("RTL_COMANDOS_ENVIADOS", "Comandos enviados");
define("RTL_POSICAO_PERIODO", "Posição período");
define("RTL_ATUACAO", "Atuação");
define("RTL_HISTORICO_DE_ATENDIMENTO", "Histórico de atendimento");
define("RTL_EXPORTAR_PARA_KML", "Exportar para KML");
define("RTL_MODIFICAR_VEICULO", "Modificar veículo");
define("RTL_SELECIONAR_ICONE", "Selecionar ícone");
define("RTL_EXPORTAR_KML", "Exportar para KML");
define("RTL_IMPRIMIR", "Imprimir");
define("RTL_PDF", "Exportar PDF");
define("RTL_EXCEL", "Exportar Excel");
define("RTL_RELATORIO", "Relatório");
define("RTL_GRID", "Grid");
define("RTL_BUSCA", "Busca");
define("RTL_BLOQUEIO", "Bloqueio");
define("RTL_VISUALIZAR_COMANDOS_ENVIADOS", "Visualizar Comandos Enviados");


define("TXT_CONFIRMA_FINALIZAR_EVENTO_PANICO", "Deseja realmente finalizar o evento de pânico?");

define("TXT_TUTORIAL_BUSCAR", "Utilize esse campo para pesquisar informações do veículo e filtrar a listagem. A busca irá procurar por: placa, complemento, nome do grupo, tipo do veículo, número de série, modelo ou fabricante do rastreador e o logradouro em que o veículo está.");
define("TXT_TUTORIAL_IGNICAO", "Filtre os veículos que estão ligados ou desligados.");
define("TXT_TUTORIAL_PANICO", "Filtre os veículos com pânico ligado ou desligado.");
define("TXT_TUTORIAL_ULTIMA_POSICAO", "Filtre os veículos que posicionaram a partir desta data.");
define("TXT_MSG_BUSCA", "Colunas de Busca: Grupo, Complemento, Número de Série, Rastreador, Logradouro e Fabricante.");