<?
define("RTL_GRAFICO_ULTIMA_HORA", "Posicionaram na última hora");
define("RTL_GRAFICO_MAIS_UMA_HORA", "Não posicionam há mais de uma hora");
define("RTL_POSICAO_PERIODO", "Posições por período");
define("RTL_GRAFICO_MAIS_TRES_HORAS", "Não posicionam há mais de três horas");
define("RTL_GRAFICO_MAIS_SEIS_HORAS", "Não posicionam há mais de seis horas");
define("RTL_GRAFICO_MAIS_DOZE_HORAS", "Não posicionam há mais de doze horas");
define("RTL_GRAFICO_MAIS_UM_DIA", "Não posicionam há mais de um dia");
define("RTL_GRAFICO_MAIS_DOIS_DIAS", "Não posicionam há mais de dois dias");
define("RTL_ABA_ULTIMA_HORA", "Posicionando");
define("RTL_ABA_MAIS_UMA_HORA", "+1 hora");
define("RTL_ABA_MAIS_TRES_HORAS", "+3 horas");
define("RTL_ABA_MAIS_SEIS_HORAS", "+6 horas");
define("RTL_ABA_MAIS_DOZE_HORAS", "+12 horas");
define("RTL_ABA_MAIS_UM_DIA", "+24 horas");
define("RTL_ABA_MAIS_DOIS_DIAS", "+48 horas");
define("RTL_POSICOES_TEMPO", "Posições por tempo");
define("RTL_POSICAO_POR_PERIODO", "Posição por período");
define("RTL_CLIQUE_PARA_DETALHES_FABRICANTE", "Clique nas legendas para ver detalhes por fabricante");
define("RTL_ACOES", "Ações");
define("RTL_ALTERADO", "Alterado");
define("RTL_ATE_600", "Até 600");
define("RLT_ENTRE_600_E_1000", "Entre 600 e 1000");
define("RLT_ENTRE_1000_E_2000", "Entre 1000 e 2000");
define("RLT_MAIOR_2000", "Maior que 2000");
define("RTL_ANALITICO", "Analítico");
define("RTL_ATUACAO", "Atuação");
define("RTL_ATE_50KM", "Até 50 km/h");
define("RTL_BATERIA", "Bateria");
define("RTL_BATENDO", "Batendo");
define("RTL_BETONEIRA", "Betoneira");
define("RTL_BLOQUEADO", "Bloqueado");
define("RTL_BLOQUEIO", "Bloqueio");
define("RTL_CADASTRAR_POSICAO_COMO_PONTO_INTERESSE", "Cadastrar posição como ponto de interesse");
define("RTL_CERCAS", "Cercas");
define("RTL_CERCAS_COLUNA", "Cercas");
define("RTL_COMANDOS", "Comandos");
define("RTL_COMANDOS_ENVIADOS", "Comandos Enviados");
define("RTL_COM_ERRO", "Com erro");
define("RTL_CONFIGURACOES", "Configurações");
define("RTL_CONTADOR", "Contador");
define("RTL_DATA_HORA_COLUNA", "Data");
define("RTL_DATA_HORA_GRAVACAO", "Data/Hora de gravação");
define("RTL_DATA_HORA_GRAVACAO_COLUNA", "Gravação");
define("RTL_DE", "De");
define("RTL_DE_50_A_100KM", "de 50 a 100 km/h");
define("RTL_DESBLOQUEADO", "Desbloqueado");
define("RTL_DESCARREGANDO", "Descarregando");
define("RTL_DESLIGADA", "Desligada");
define("RTL_DESLIGADO", "Desligado");
define("RTL_EMAIL", "Email");
define("RTL_ERRO_CRITICO", "Erro crítico");
define("RTL_EVENTO", "Evento");
define("RTL_EVENTOS_ATIVOS", "Eventos Ativos");
define("RTL_EVENTOS_FINALIZADOS", "Eventos Finalizados");
define("RTL_EVENTOS_GERADOS", "Eventos Gerados");
define("RTL_EVENTOS_GERADOS_FINALIZADOS", "Eventos Gerados x Eventos Finalizados");
define("RTL_EXCEL", "Excel");
define("RTL_EXPORTAR_KML", "Exportar KML");
define("RTL_FILTRAR_POR", "Filtrar por");
define("RTL_FINALIZAR_EVENTO", "Finalizar Evento");
define("RTL_GERAR", "Gerar");
define("RTL_HORIMETRO", "Horímetro");
define("RTL_HORIMETRO_COLUNA", "HOR");
define("RTL_HORIMETRO_PARCIAL", "Horímetro Parcial");
define("RTL_HORIMETRO_PARCIAL_COLUNA", "HOR Parcial");
define("RTL_IGNICAO", "Ignição");
define("RTL_IMPRIMIR", "Imprimir");
define("RTL_INFO", "Ícones de informação");
define("RTL_INFO_COLUNA", "Info");
define("RTL_INFORMACOES_DE_HORIMETRO", "Informações de Horímetro");
define("RTL_INFORMACOES_DE_ODOMETRO", "Informações de Hodômetro");
define("RTL_INTERVALO_DE_POSICAO", "Intervalo de posição");
define("RTL_INTERVALO_TOTAL", "Intervalo total");
define("RTL_LATITUDE_LONGITUDE", "Latitude e Longitude");
define("RTL_LATITUDE_LONGITUDE_COLUNA", "Lat/Long");
define("RTL_LIGADA", "Ligada");
define("RTL_LIGADO", "Ligado");
define("RTL_LISTAGEM_VEICULOS_VELOCIDADE_EXCEDIDA", "Listagem de Veículos");
define("RTL_LOGRADOURO", "Logradouro");
define("RTL_MAIOR_100KM", "maior que 100 km/h");
define("RTL_MAIORES_VELOCIDADES", "Maiores velocidades");
define("RTL_MEMORIA", "Memoria");
define("RTL_MEMORIA_COLUNA", "MEM");
define("RTL_MILHAS_NAUTICAS", "Milhas Náuticas");
define("RTL_MINUTOS", "minutos");
define("RTL_MODIFICAR", "Modificar Velocidade Máxima");
define("RTL_MOTIVO", "Motivo");
define("RTL_MOTIVO_COLUNA", "MOT");
define("RTL_NENHUM", "Nenhum");
define("RTL_NIVEL_BATERIA", "Nível de bateria");
define("RTL_NOME_MOTORISTA", "Nome do Motorista");
define("RTL_NOME_MOTORISTA_COLUNA", "Motorista");
define("RTL_NORMAL", "Normal");
define("RTL_NUMERO_SATELITES_COLUNA", "Satélites");
define("RTL_OBSERVACAO", "Observação");
define("RTL_OBSERVACAO_COLUNA", "Obs");
define("RTL_ODOMETRO", "Hodômetro");
define("RTL_ODOMETRO_COLUNA", "HOD");
define("RTL_ORIGEM_DESTINO", "Origem/Destino");
define("RTL_ORIGEM_DESTINO_COLUNA", "Origem/Destino");
define("RTL_PANICO", "Pânico");
define("RTL_PARA", "Para");
define("RTL_PARADO", "Parado");
define("RTL_PDF", "PDF");
define("RTL_PLACA_ROTULO", "Rótulo/Placa");
define("RTL_PLACA_ROTULO_COLUNA", "Placa");
define("RTL_POSICOES", "Posições por Velocidade");
define("RTL_QUANTIDADE_POSICOES", "Quantidade de Posições");
define("RTL_QUANTIDADE_POSICOES_POR_VEICULO", "Quantidade de posições por veículo");
define("RTL_QUILOMETRAGEM_PERCORRIDA_ODOMETRO", "Quilometragem Percorrida Hodômetro");
define("RTL_QUILOMETRAGEM_PERCORRIDA_PONTO_A_PONTO", "Quilometragem Percorrida Ponto a Ponto");
define("RTL_REGISTRO_POR_PAGINA", "Registros por Página");
define("RTL_REGISTROS", "registros");
define("RTL_RELATORIO", "Relatório");
define("RTL_SMS", "SMS");
define("RTL_STATUS_DAS_PORTAS", "Status das portas");
define("RTL_STATUS_DAS_PORTAS_COLUNA", "Portas");
define("RTL_TELEMETRIA", "Telemetria");
define("RTL_TEMPO_IGNICAO_DESLIGADA", "Tempo com ignição desligada");
define("RTL_TEMPO_IGNICAO_LIGADA", "Tempo com ignição ligada");
define("RTL_TENSAO", "Tensão");
define("RTL_TODAS", "Todas");
define("RTL_EM_PANICO", "Pânico");
define("RTL_TODOS_NO_MAPA", "Todos no Mapa");
define("RTL_TRANSMISSAO_COLUNA", "Transm");
define("RTL_ULTIMA_SEMANA", "Última Semana");
define("RTL_ULTIMOS_4_MESES", "Últimos 4 Meses");
define("RTL_VEICULO", "Veículo");
define("RTL_VEICULOS", "Veículos");
define("RTL_VEICULOS_POR_QUANTIDADE_POSICOES", "Veículos por quantidade posições");
define("RTL_VELOCIDADE", "Velocidade");
define("RTL_VELOCIDADE_COLUNA", "Velocidade");
define("RTL_VELOCIDADE_MINIMA", "Km/h Mínima");
define("RTL_VELOCIDADE_MAXIMA", "Km/h Máxima");
define("RTL_VER_NO_MAPA", "Ver no Mapa");
define("RTL_VISUALIZAR_COMANDOS_ENVIADOS", "Visualizar Comandos Enviados");
define("RTL_VISUALIZAR_POSICAO_NO_MAPA", "Visualizar posição no Mapa");
define("RTL_TITULO_MAPA", "Ultima posição de todos os veículos");
define("RTL_INFORMACOES_MILHAS_NAUTICAS", "Informações de milhas náuticas");
define("RTL_MILHAS_NAUTICAS_PERCORRIDA_PONTO_A_PONTO", "Milhas náuticas percorridas ponto a ponto");
define("RTL_STATUS_PORTA", "Status da porta");
define("RTL_INCLUSIVO", "inclusivo");
define("RTL_EXCLUSIVO", "exclusivo");
define("RTL_SENSOR_TEMPERATURA", "Sensor de temperatura");
define("RTL_UMIDADE", "Umidade");
define("TXT_ALERT_SUCESSO_MODIFICAR", "Sucesso ao modificar o registro.");
define("TXT_CONFIRMA_FINALIZAR_EVENTO", "Deseja realmente finalizar este evento?");
define("TXT_ERRO_DATA_HORA_FIM", "Selecione uma data/hora final para gerar o relatório<br/>");
define("TXT_ERRO_DATA_HORA_INICIO", "Selecione uma data/hora inicial para gerar o relatório<br/>");
define("TXT_ERRO_ID_VEICULO_GRUPO", "Selecione um grupo ou um veículo para gerar o relatório<br/>");
define("TXT_ERRO_INICIO_MAIOR_FIM", "A data inicial é posterior à data final.<br/>");
define("TXT_SALVO_AUTOMATICAMENTE", "As configurações são salvas automaticamente.");
define("TXT_CALCULO_ODOMETRO_GPS_CADASTRADO,'"Cálculo feito pelo sistema em cada ponto!"');
define("TXT_CALCULO_PONTO_A_PONTO,'"Cálculo feito com valores de odômetro de GPS previamente cadastrado!"');
define("TXT_ERRO_VELOCIDADE,'A velocidada mínima não pode ultrapassar o valor da velocidade máxima!');
define("RTL_RPM ,'RPM');


//defines dos rótulos do tutorial
define("TXT_TUTORIAL_POSICOES_VEICULO", "Gráfico de porcentagem de veículos que possuem alteração no número de posições.");
define("TXT_TUTORIAL_TEMPO", "Gráfico quantitativo de veículos que possuem atraso no envio de posições.");
define("TXT_TUTORIAL_GRUPO", "Campo de Busca de grupo.");
define("TXT_TUTORIAL_VEICULO", "Campo de Busca de veículo.");
define("TXT_TUTORIAL_DATA_HORA_INICIAL", "Selecione a data/hora inicial desejada.");
define("TXT_TUTORIAL_DATA_HORA_FINAL", "Selecione a data/hora final desejada.");
define("TXT_TUTORIAL_VEL_MIN", "Velocidade mínima das posições que serão pesquisadas.");
define("TXT_TUTORIAL_FILTRAR", "Selecione o tipo de filtro desejado para o relatório.");
define("TXT_TUTORIAL_INTERVALO", "Intervalo mínimo entre cada posição.");
define("TXT_TUTORIAL_REGISTRO", "Número de registros que será exibido por página no relatório.");
define("TXT_TUTORIAL_IGNICAO", "Filtre as posições pela ignição do veículo.");
define("TXT_TUTORIAL_TODOS_NO_MAPA", "Visualize o rastro de todas as posições no mapa.");
define("TXT_TUTORIAL_EXPORTAR_KML", "Exportar KML.");
define("TXT_TUTORIAL_COMANDOS", "Listagem de comandos enviados para o veículo pesquisado.");
define("TXT_TUTORIAL_CONFIGURACOES", "Configuração de quais colunas serão visualizadas na listagem.");

