<?php
define("RTL_JORNADA_DETALHADA", "Jornada detalhada");
define("RTL_DATA", "Data");
define("RTL_PLACA", "Placa");
define("RTL_JORNADA", "Jornada");
define("RTL_COMPLEMENTO_PLACA", "Complemento");
define("RTL_INICIO_JORNADA", "Início da Jornada");
define("RTL_FIM_JORNADA", "Final da Jornada");
define("RTL_INTER_JORNADA", "Inter jornada");
define("RTL_TOTAL_JORNADA", "Total da jornada");
define("RTL_MAXIMA_DIRECAO_CONTINUA", "Maior direção contínua");
define("RTL_DIRECAO", "Direção");
define("RTL_DESCANSO", "Descanso");
define("RTL_ALIMENTACAO", "Alimentação");
define("RTL_ADICIONAL_NOTURNO", "Adicional noturno");
define("RTL_HORA_EXTRA", "Hora extra");
define("RTL_INTRA_JORNADA", "Intra jornada");
define("RTL_PRIMEIRO_DIA", "Primeiro dia");
define("RTL_ESPERA", "Tempo de espera");
define("RTL_TOTAIS", "Totais");
define("RTL_PERNOITE", "Pernoite");
define("RTL_DIAS", "Qtd. dias");
define("RTL_PRIMEIRO_INICIO", "Primeiro início");
define("RTL_ULTIMO_FIM", "Último fim");
define("RTL_TOLERANCIA", "Tolerância");
define("RTL_HORA_MINIMA", "Hora mínima");
define("RTL_ESTRUTURA_RELATORIO", "Estrutura do Relatório");
define("RTL_GERENCIAL", "Gerencial");
define("RTL_SIMPLIFICADO", "Simplificado");
define("RTL_DESCANSO_PERNOITE", "Descanso + Pernoite");
define("TXT_AVISO_JORNADA_DETALHADA ", "Antes de exportar (PRINT, PDF, XLSX) o relatório deve ser gerado e todos os veículos devem terminar o carregamento.<br/>Buscas por grupo para mais de 7 dias tendem a ser mais lentas.");
define("RTL_EM_DIRECAO ", "Em Direção");
define("RTL_JORNADA_DETALHADA_INTERVALO ", "Jornada detalhada com Intervalos");
define("RTL_ADICIONAR_PARADA_ESPERA ", "Adicionar Parada Espera");
define("RTL_JORNADA_DETALHADA_COM_PARADAS ", "Jornada detalhada com Paradas");
define("RTL_VEICULO ", "Veículo");
define("RTL_TOTAL_HORAS_VIAGEM ", "Total Horas Viagem");
define("RTL_PARADAS_REFEICAO ", "Paradas/Refeição");
define("RTL_HORAS_EM_ESPERA ", "Horas em Espera");
define("RTL_HORAS_EXTRAS ", "Horas Extras");