<?
define("RTL_ID", "Id");
define("RTL_ID_VEICULO", "Id Veiculo");
define("RTL_ID_MOTORISTA", "Id Motorista");
define("RTL_ID_SINISTRO_RESPONSAVEL", "Id Sinistro Responsavel");
define("RTL_DATA_HORA", "Data Hora");
define("RTL_LOGRADOURO", "Logradouro");
define("RTL_ESTADO", "Estado");
define("RTL_CIDADE", "Cidade");
define("RTL_PAIS", "Pais");
define("RTL_NOME_TERCEIRO", "Nome Terceiro");
define("RTL_CONTATO_TERCEIRO", "Contato Terceiro");
define("RTL_SEGURADORA", "Seguradora");
define("RTL_BOLETIM_OCORRENCIA", "Boletim Ocorrência");
define("RTL_DESCRICAO_SINISTRO", "Descrição Sinistro");
define("RTL_DANOS_OCORRIDOS", "Danos Ocorridos");
define("RTL_DESCRICAO_LISTAGEM_MANUTENCAO_SINISTRO", "Listagem de Manutenção Sinistro");
define("TXT_ALERT_SUCESSO_MODIFICAR", "Sucesso ao modificar registro");
define("TXT_ALERT_ERRO_OPERACAO", "Erro ao executar operação");
define("TXT_ALERT_SUCESSO_OPERACAO", "Sucesso ao executar operação");
define("TXT_ALERT_SUCESSO_ADICIONAR", "Sucesso ao Adicionar registro");
define("TXT_CONFIRME_DELETE_REGISTROS", "Deseja realmente remover este(s) registro(s)?");
define("TXT_CONFIRMACAO_DELETE_REGISTROS", "Registros foram excluidos com exito");
define("TXT_ERRO_DELETAR_REGISTROS", "Erro ao Excluir registros");
define("TXT_ERRO_NENHUM_REGISTRO_SELECIONADO", "Por favor, selecione itens para serem excluidos");
define("TXT_ATENCAO", "Atenção");
define("TXT_PREENCHA_CAMPOS_OBRIGATORIOS", "Por favor preencher todos os campos obrigatórios");
define("RTL_MODIFICAR_MANUTENCAO_SINISTRO", "Modificar Manutenção Sinistro");
define("RTL_ADICIONAR_MANUTENCAO_SINISTRO", "Adicionar Manutenção Sinistro");

define("RTL_MANUTENCAO_SINISTRO", "Sinistros");
define("RTL_MODIFICANDO_SINISTRO", "Modificando sinistro");
define("RTL_MODIFICAR_SINISTRO", "Modificar sinistro");
define("RTL_MOTORISTA", "Motorista");
define("RTL_ENDERECO", "Endereço");
define("RTL_RESPONSAVEL", "Responsável");
define("RTL_ROTULO_VEICULO", "Veículo");
define("RTL_NOME_MOTORISTA", "Nome do motorista");
define("RTL_RESPONSAVEL_SINISTRO", "Responsável pelo sinistro");
define("RTL_SUBIR_ARQUIVO", "Subir arquivo");
define("RTL_ANEXOS_UPADOS", "Anexos");
define("RTL_NOME", "Nome");
define("RTL_FORMATO", "Formato");
define("RTL_DOWNLOAD", "Download");