<?
define("RTL_ABRIR_MOTORISTA", "Abrir Motorista");
define("RTL_ADICIONAR_MOTORISTA", "Adicionar Motorista");
define("RTL_BAIRRO", "Bairro");
define("RTL_CATEGORIA_CNH", "Categoria");
define("RTL_CATEGORIAS_CNH", "Categorias CNH");
define("RTL_CELULAR", "Celular");
define("RTL_CEP", "CEP");
define("RTL_CHECKBOX_EXCLUIR", "Caixa de seleção");
define("RTL_CIDADE", "Cidade");
define("RTL_CNH", "CNH");
define("RTL_COM_FOTO", "Com foto");
define("RTL_COMPLEMENTO", "Complemento");
define("RTL_CONTATO", "Contato");
define("RTL_CPF", "CPF");
define("RTL_DADOS", "Dados");
define("RTL_DATA_HORA_CADASTRO", "Data Hora Cadastro");
define("RTL_DESCRICAO_LISTAGEM_MOTORISTA", "Listagem de Motorista");
define("RTL_DESVINCULADO", "Desvinculado");
define("RTL_EMAIL", "Email");
define("RTL_ENDERECO", "Endereço");
define("RTL_FIM_JORNADA", "Fim da jornada");
define("RTL_FOTO", "Foto");
define("RTL_ID", "Id");
define("RTL_ID_ENDERECO", "Id Endereco");
define("RTL_ID_GRUPO", "Id Grupo");
define("RTL_ID_NEXTEL", "ID Nextel");
define("RTL_INATIVO", "Inativo");
define("RTL_INDICADORES", "Indicadores");
define("RTL_INICIO_JORNADA", "Início da jornada");
define("RTL_LOGRADOURO", "Logradouro");
define("RTL_MODIFICAR_MOTORISTA", "Modificar Motorista");
define("RTL_MOTORISTA", "Motorista");
define("RTL_MOTORISTAS", "Motoristas");
define("RTL_MOTORISTAS_VINCULADOS", "Motoristas vinculados a um veículo");
define("RTL_NEXTEL", "Nextel");
define("RTL_NOME", "Nome");
define("RTL_NUMERO", "Número");
define("RTL_OBSERVACAO", "Observação");
define("RTL_PRIMEIRA_CNH", "Primeira CNH");
define("RTL_QUANTITATIVO_FOTOS", "Motoristas que possuem foto");
define("RTL_REFERENCIA", "Referência");
define("RTL_REMOVER_FOTO", "Remover Foto");
define("RTL_SEM_FOTO", "Sem foto");
define("RTL_STATUS", "Status");
define("RTL_TELEFONE", "Telefone");
define("RTL_UF", "UF");
define("RTL_VALIDADE_CNH", "Prazos de vencimento de CNH");
define("RTL_VENCEM_ATE_60_DIAS", "Vencimento em até 60 dias");
define("RTL_VENCEM_MAIS_60_DIAS", "Vencem em mais de 60 dias");
define("RTL_VENCIDAS", "CNH vencidas");
define("RTL_VIGENCIA_NORMAL", "Vigência normal");
define("RTL_VINCULADO", "Vinculado");
define("RTL_COMPARTILHAR_FILHOS", "Compartilhar com filhos");
define("RTL_ENVIAR_EMAIL", "Enviar email");
define("RTL_MOTORISTA_SUPERVISOR", "Motorista supervisor");
define("RTL_MOTORISTA_GERENTE", "Motorista gerente");
define("RTL_SENHA_APP", "Senha Aplicativo Teclado");
define("RTL_DADOS_APP", "Dados App");
define("RTL_DADOS_EXTRAS", "Dados Extras");
define("RTL_SUBIR_ARQUIVO", "Subir Arquivo");
define("ROTULO_IMPORTACAO_MOTORISTA", "Importação Motorista");
define("RTL_PRIORIZAR_CATEGORIA", "Priorizar categoria selecionada");
define("RTL_RESULTADO_IMPORTACAO", "Resultado Importação");
define("RTL_MODELO", "Modelo Arquivo");
define("RTL_ANEXOS", "Anexos");
define("TXT_TAMANHO_ANEXO_MAIOR", "Tamanho do arquivo de anexo maior que o limite permitido");

define("RTL_VALOR_KM", "Valor do Km");
define("RTL_KM_DESCONTO", "Km Desconto");
define("RTL_UNIDADE", "Unidade");
define("RTL_CARGO", "Cargo");
define("RTL_CENTRO_CUSTO", "Centro de Custo");
define("RTL_STATUS_IMPORTACAO", "Status Importação Motorista");
define("RTL_STATUS_VINCULO", "Status Vínculo com Veículo");

define("TXT_ALERT_SUCESSO_MODIFICAR", "Sucesso ao modificar registro");
define("TXT_ALERT_SUCESSO_ADICIONAR", "Sucesso ao Adicionar registro");
define("TXT_CEP_OBRIGATORIO", "Um CEP deve ser digitado");
define("TXT_CNH_VENCIDA", "Essa CNH está vencida");
define("TXT_CONFIRMAR_REMOCAO_FOTO", "Deseja realmente remover a foto desse motorista?");
define("TXT_CPF_INVALIDO", "CPF inválido");
define("TXT_EXCESSO_CATEGORIAS", "Selecione apenas 2 categorias");
define("TXT_FORMATO_FOTO_INVALIDO", "Formato da foto inválido");
define("TXT_MOTORISTA_CNH_INVALIDA", "Essa CNH é inválida");
define("TXT_MOTORISTA_CNH_REPETIDO", "Essa CNH já está cadastrada.");
define("TXT_MOTORISTA_CPF_REPETIDO", "Esse CPF já está cadastrado.");
define("TXT_PREENCHA_CAMPOS_OBRIGATORIOS", "Por favor preencher todos os campos obrigatórios");
define("TXT_CATEGORIAS_ERRADAS", "Por favor selecionar corretamente as categorias");

//defines dos rótulos do tutorial
define("TXT_TUTORIAL_CNH", "Gráfico quantitativo de prazo de vencimento de CNH de motoristas cadastrados no sistema. Clique na barra vermelha de CNH vencida para ser direcionado para a listagem filtrada de motoristas com CNH vencida.");
define("TXT_TUTORIAL_ADICIONAR", "Botão para adicionar novos motoristas ao sistema.");
define("TXT_TUTORIAL_LISTAGEM", "Clique em colunas que possuem as setas para ordenar os registros. Os ícones da última coluna da direita possuem ações para cada registro. Os registros em vermelho são os motoristas que possuem CNH vencidas.");
define("TXT_TUTORIAL_RFID", "Número identificador do cartão do motorista.");
define("TXT_TUTORIAL_STATUS", "O status identifica se o motorista está em atividade ou não.");
define("TXT_MSG_BUSCA", "Colunas de Busca: Nome, CNH, Categoria, CPF, RFID e ID.");