<?
define("RTL_ID", "Id");
define("RTL_ID_VEICULO", "Id Veiculo");
define("RTL_ID_MULTA", "Id Multa");
define("RTL_ID_MULTA_SITUACAO", "Id Multa Situacao");
define("RTL_ID_MULTA_PENALIDADE", "Id Multa Penalidade");
define("RTL_ID_MOTORISTA", "Id Motorista");
define("TXT_ALERT_SUCESSO_MODIFICAR", "Sucesso ao modificar registro");
define("TXT_ALERT_ERRO_OPERACAO", "Erro ao executar operação");
define("TXT_ALERT_SUCESSO_OPERACAO", "Sucesso ao executar operação");
define("TXT_ALERT_SUCESSO_ADICIONAR", "Sucesso ao Adicionar registro");
define("TXT_CONFIRME_DELETE_REGISTROS", "Deseja realmente remover este(s) registro(s)?");
define("TXT_CONFIRMACAO_DELETE_REGISTROS", "Registros foram excluidos com exito");
define("TXT_ERRO_DELETAR_REGISTROS", "Erro ao Excluir registros");
define("TXT_ERRO_NENHUM_REGISTRO_SELECIONADO", "Por favor, selecione itens para serem excluidos");
define("TXT_ATENCAO", "Atenção");
define("TXT_PREENCHA_CAMPOS_OBRIGATORIOS", "Por favor preencher todos os campos obrigatórios");
define("RTL_MANUTENCAO_MULTA", "Manutencao Multa");
define("RTL_MODIFICAR_MANUTENCAO_MULTA", "Modificar Manutencao Multa");
define("RTL_ADICIONAR_MANUTENCAO_MULTA", "Adicionar Manutencao Multa");
define("RTL_LOGRADOURO", "Logradouro");
define("RTL_DATA_HORA_INFRACAO", "Data/hora da infração");
define("RTL_CODIGO_QUALIFICACAO", "Código da infração");
define("RTL_SITUACAO_INFRACAO", "Situação da infração");
define("RTL_AIT", "Auto de Infração de Trânsito");
define("RTL_ENDERECO", "Endereço");
define("RTL_CIDADE", "Cidade");
define("RTL_ESTADO", "Estado");
define("RTL_PAIS", "País");
define("RTL_MOTORISTA", "Motorista");
define("RTL_CODIGO_NOTIFICACAO", "Código da Notificação");
define("RTL_DATA_HORA_IMPRESSAO_NOTIFICACAO", "Data/hora da impressão da notificação");
define("RTL_DATA_DEFESA_NOTIFICACAO", "Data da defesa da notificação");
define("RTL_DATA_IMPRESSAO_PENALIDADE", "Data da impressão da penalidade");
define("RTL_DATA_VENCIMENTO_PENALIDADE", "Data de vencimento da penalidade");
define("RTL_VALOR_PENALIDADE", "Valor da penalidade");
define("RTL_VALOR_DESCONTO_PENALIDADE", "Valor de desconto da penalidade");
define("RTL_SITUACAO_INFRACAO", "Situação da infração");
define("RTL_DESCRICAO_PENALIDADE", "Descrição da penalidade");
define("RTL_OBSERVACAO", "Observação");
define("RTL_DATA_ENVIO_NOTIFICACAO", "Data do envio da notificação");
define("RTL_DATA_ENVIO_RH", "Data do envio RH");
define("RTL_MODIFICANDO_MULTA", "Modificando multa");
define("RTL_MULTAS", "Multas");
define("RTL_NOME", "Nome");
define("RTL_FORMATO", "Formato");
define("RTL_DOWNLOAD", "Download");
define("RTL_SUBIR_ARQUIVO", "Subir arquivo");
define("RTL_ANEXOS_UPADOS", "Anexos");
define("RTL_ARQUIVOS", "Arquivos");
define("RTL_MODIFICAR_MULTA", "Modificar multa");