<?php
define("RTL_STATUS_POSICAO", "Status de posição");
define("RTL_GRAFICO_ULTIMA_HORA", "Posicionaram na última hora");
define("RTL_GRAFICO_MAIS_UMA_HORA", "Não posicionam há mais de uma hora");
define("RTL_GRAFICO_MAIS_TRES_HORAS", "Não posicionam há mais de três horas");
define("RTL_GRAFICO_MAIS_SEIS_HORAS", "Não posicionam há mais de seis horas");
define("RTL_GRAFICO_MAIS_DOZE_HORAS", "Não posicionam há mais de doze horas");
define("RTL_GRAFICO_MAIS_UM_DIA", "Não posicionam há mais de um dia");
define("RTL_GRAFICO_MAIS_DOIS_DIAS", "Não posicionam há mais de dois dias");
define("RTL_GRAFICO_NAO_POSICIONARAM", "Não posicionaram ainda");
define("RTL_VER_DETALHES", "Clique para ver detalhes da");
define("RTL_POSICOES_TEMPO", "Posições por tempo");
define("RTL_CLIQUE_PARA_DETALHES_FABRICANTE", "Clique nas legendas para ver detalhes por fabricante");
define("RTL_CLIQUE_PARA_DETALHES_OPERADORA", "Clique nas legendas para ver detalhes por operadora");
define("RTL_TOTAL_POSICIONANDO", "Total posicionando");
define("RTL_POSICIONANDO", "posicionando");
define("RTL_CLIQUE_PARA_VOLTAR", "Shift + clique para voltar aos fabricantes");
define("RTL_VER_DETALHES_ABA", "Clique nas colunas para ver detalhes em uma nova aba");
define("RTL_VOLTAR", "Voltar");
define("RTL_FILTRAR_POR", "Filtrar por: ");
define("RTL_ABA_ULTIMA_HORA", "Posicionando");
define("RTL_ABA_MAIS_UMA_HORA", "+1 hora");
define("RTL_ABA_MAIS_TRES_HORAS", "+3 horas");
define("RTL_ABA_MAIS_SEIS_HORAS", "+6 horas");
define("RTL_ABA_MAIS_DOZE_HORAS", "+12 horas");
define("RTL_ABA_MAIS_UM_DIA", "+24 horas");
define("RTL_ABA_MAIS_DOIS_DIAS", "+48 horas");
define("RTL_ABA_NAO_POSICIONARAM", "Não posicionou");
define("RTL_ROTULO_NUM_SERIE", "Rótulo (número de série)");
define("RTL_COMPARA_DATA_HORA", "Data/Hora | Data/Hora gravação");
define("RTL_ADICIONAR_HISTORICO", "Adicionar histórico");
define("RTL_HISTORICO_ACOES", "Histório de ações");
define("RTL_TOMADA_HA", "Tomada há...");
define("RTL_QUANDO_ESTAVA", "Quanto estava...");
define("RTL_TOTAL", "Total");
define("RTL_ACAO_REALIZADA_RECENTEMENTE", "Ação realizada recentemente");
define("RTL_ABA_TODOS", "Todos");

define("RTL_HISTORICO_POSICIONANDO ", "posicionando normalmente.");
define("RTL_HISTORICO_UMA_HORA ", "há +1 hora sem posicionar.");
define("RTL_HISTORICO_TRES_HORAS ", "há +3 horas sem posicionar.");
define("RTL_HISTORICO_SEIS_HORAS ", "há +6 horas sem posicionar.");
define("RTL_HISTORICO_DOZE_HORAS ", "há +12 horas sem posicionar.");
define("RTL_HISTORICO_UM_DIA ", "há +24 horas sem posicionar.");
define("RTL_HISTORICO_DOIS_DIAS ", "há +48 horas sem posicionar.");
define("RTL_HISTORICO_SEM_POSICOES ", "sem nenhuma posição enviada.");
define("RTL_ATRAS", "atrás.");
define("RTL_MAIS_DOIS_DIAS", "mais de dois dias.");
define("RTL_ULTIMA_ACAO_TOMADA_HA", "Última ação tomada há");
define("RTL_CLIQUE_HISTORICO", "Clique para ver o histórico.");
define("RTL_QUANDO_VEICULO_ESTAVA", "quando o veículo estava");
define("RTL_NENHUMA_ACAO", "Nenhuma ação tomada recentemente");

define("TXT_MUITOS_VEICULOS", "Veículos demais selecionados. O limite é 200.");
define("TXT_SELECIONE_VEICULOS", "Selecione pelo menos 1 veículo");
define("TXT_ERRO_ABA_ABERTA", "Essa aba já está aberta.");
define("TXT_CONTINUAR_TUTORIAL", "Ao continuar, todas as abas abertas serão fechadas. Deseja ver o tutorial?");

define("TXT_TUTORIAL_ATENCAO", "Leia o aviso no popup abaixo.");
define("RTL_GRAFICOS", "Gráficos");
define("RTL_ADICIONAR_HISTORICO", "Adicionar histórico");
define("RTL_NOVAS_ABAS", "Novas abas");
define("RTL_MONITORAR", "Monitorar");
define("TXT_TUTORIAL_GRAFICOS", "Os gráficos representam a quantidade de veículos que posicionaram em cada faixa de tempo. Ao clicar nas colunas do gráfico, será mostrado o gráfico quantitativo por fabricante ou operadora, de acordo com o que estiver selecionado nos botões no canto superior esquerdo.");
define("TXT_TUTORIAL_NOVAS_ABAS", "Ao clicar novamente no gráfico, uma nova aba será aberta com todos os veículos que estão no filtro selecionado. Ao clicar em próximos, serão visualizados todos os veículos que posicionaram na última hora para o primeiro fabricante do gráfico (da esquerda para direita).");
define("TXT_TUTORIAL_MONITORAR", "Selecione os veículos que deseja ver e clique aqui para ser direcionado ao monitorar e visualizá-los no mapa.");
define("TXT_TUTORIAL_ADICIONAR_HISTORICO", "Cada veículo possui um histórico de atendimento. Os pontos de exclamação em vermelho significam que nenhum contato foi feito desde que o veículo entrou nessa faixa de tempo de posicionamento. Os pontos de exclamação em amarelo significam que um contato já foi feito recentemente, mas o veículo subiu uma faixa de atraso no posicionamento (por exemplo, de 1 hora de atraso para 3 horas de atraso). Já os Pontos de exclamação em verde significam que o contato foi feito recentemente com o cliente.");
define("TXT_ESPELHAR_HISTORICO", "Deseja espelhar esse histórico para que ele apareça também na Tela Central?");