<?
define("RTL_ABRIR_USUARIO", "Abrir Usuário");
define("RTL_ADICIONAR_USUARIO", "Adicionar Usuário");
define("RTL_AINDA_NAO_ENTROU", "Ainda não entrou");
define("RTL_BAIRRO", "Bairro");
define("RTL_CELULAR", "Celular");
define("RTL_CEP", "CEP");
define("RTL_CIDADE", "Cidade");
define("RTL_COMPLEMENTO", "Complemento");
define("RTL_CONFIRMAR_SENHA", "Confirmar Senha");
define("RTL_CPF_CNPJ", "Cpf Cnpj");
define("RTL_DATA_HORA_CADASTRO", "Data Hora Cadastro");
define("RTL_DATA_HORA_EXPIRADO", "Data Hora Expirado");
define("RTL_CONFIGURAR_USUARIO", "Configurar Usuário");
define("RTL_DESCRICAO_LISTAGEM_USUARIO", "Listagem de usuário");
define("RTL_EMAIL", "Email");
define("RTL_EXPIRA_EM", "Expira em");
define("RTL_FOTO", "Foto");
define("RTL_ID", "Id");
define("RTL_ID_ENDERECO", "Id Endereco");
define("RTL_ID_FUSO_HORARIO", "Id Fuso Horario");
define("RTL_ID_GRUPO", "Id Grupo");
define("RTL_ID_NEXTEL", "ID Nextel");
define("RTL_LISTAGEM_USUARIO", "Listagem de Usuários");
define("RTL_LOGRADOURO", "Logradouro");
define("RTL_MASTER", "Master");
define("RTL_MENSAGEM", "Mensagem");
define("RTL_MODIFICAR_USUARIO", "Modificar Usuário");
define("RTL_NAO", "Não");
define("RTL_NEXTEL", "Nextel");
define("RTL_NOME", "Nome");
define("RTL_NOME_FUSO_HORARIO", "Horário de...");
define("RTL_NUMERO", "Número");
define("RTL_OBSERVACAO", "Observação");
define("RTL_PATCH_ATUALIZACAO", "Patch Atualizacao");
define("RTL_PLACEHOLDER_BUSCA_GRUPO", "Digite o nome do grupo desejado");
define("RTL_PERGUNTA_SENHA", "Pergunta Senha");
define("RTL_MODIFICAR_FOTO", "Modificar foto");
define("RTL_REFERENCIA", "Referência");
define("RTL_REMOVER_FOTO", "Remover Foto");
define("RTL_RESPOSTA_SENHA", "Resposta Senha");
define("RTL_SELECIONAR_GRUPO", "Selecione o grupo");
define("RTL_SENHA", "Senha");
define("RTL_SENHA_PROVISORIA", "Senha Provisoria");
define("RTL_SIM", "Sim");
define("RTL_TELEFONE", "Telefone");
define("RTL_TIPO_ACESSO", "Tipo Acesso");
define("RTL_UF", "UF");
define("RTL_USUARIO", "Usuário");
define("RTL_VINCULAR_GRUPOS", "Vincular Grupos");
define("RTL_VINCULAR_GRUPOS_USUARIO", "Vincular grupos ao usuário");
define("TXT_ALERT_SUCESSO_ADICIONAR", "Sucesso ao Adicionar registro");
define("TXT_ALERT_SUCESSO_MODIFICAR", "Sucesso ao modificar registro");
define("TXT_CEP_OBRIGATORIO", "Um CEP deve ser digitado");
define("TXT_CONFIRMAR_REMOCAO_FOTO", "Deseja realmente remover a foto desse usuário?");
define("TXT_EMAIL_COMO_USUARIO", "O email será utilizado como login para o usuário.");
define("TXT_FORMATO_FOTO_INVALIDO", "Formato Inválido, por favor somente extensões (Jpeg,Jpg,Png,BMP)");
define("TXT_LETRA_NUMERO_SENHA", "Sua senha precisa de pelo menos 1 letra e um número.");
define("TXT_PREENCHA_CAMPOS_OBRIGATORIOS", "Por favor preencher todos os campos obrigatórios");
define("TXT_SENHA_AINDA_INVALIDA", "A sua senha ainda não é válida!");
define("TXT_SENHA_CURTA", "Sua senha é curta demais!");
define("TXT_SENHA_LONGA", "Sua senha é longa demais!");
define("TXT_SENHA_INCOMPATIVEL", "A senha e a confirmação não são iguais!");
define("TXT_SENHA_INVALIDA", "Sua senha precisa de pelo menos 1 número e 1 letra.");
define("TXT_SENHAS_DIFERENTES", "As senhas são diferentes!");
define("TXT_TAMANHO_SENHA", "Sua senha precisa ter entre 8 e 32 caracteres.");
define("TXT_USUARIO_EXISTENTE", "Esse email já existe em outro usuário ativo. Favor escolher outro.");
define("TXT_USUARIO_INVALIDO", "Usuário inválido.");
define("TXT_USUARIO_TAMANHO_INVALIDO", "Use um login que tenha entre 3 e 30 caracteres.");
define("RTL_VALIDADO", "Validado");
define("RTL_NAO_VALIDADO", "Não validado");
define("RTL_ESTADO_FUSO_HORARIO", "Estado (fuso horário)");


//defines dos rótulos do tutorial
define("TXT_TUTORIAL_ADICIONAR", "Botão para adicionar novos usuários ao sistema");
define("TXT_TUTORIAL_IMPRIMIR", "Gera uma listagem para ser impressa.");
define("TXT_TUTORIAL_PDF", "Gera um arquivo PDF que pode ser salvo no computador, diretamente da listagem.");
define("TXT_TUTORIAL_CONFIGURACOES", "Nas configurações da listagem é possível remover colunas que não gostaria de visualizar, personalizando a listagem com as colunas de acordo com as preferências do usuário.");
define("TXT_TUTORIAL_FILTROS", "Selecione um filtro para ordenar a visualização.");
define("TXT_TUTORIAL_VISUALIZACAO", "Alterna a listagem entre uma visualização em quadros, com informações mais resumidas e outras funcionalidades, como excluir registro por registro mais rapidamente; e o padrão em grid, com mais detalhamento de informações.");
define("TXT_TUTORIAL_BUSCA", "Digite algo para buscar e aperte enter ou clique na lupa para iniciar a pesquisa. Dessa forma, serão filtrados registros que contenham o texto buscado.");
define("TXT_TUTORIAL_LISTAGEM", "Clique em colunas que possuem as setas para ordenar os registros. Os ícones da última coluna da direita possuem ações para cada registro.");
define("TXT_TUTORIAL_DADOS_USUARIO", "Nessa aba estão todas as informações principais do usuário.");
define("TXT_TUTORIAL_NOME", "Nome completo do usuário.");
define("TXT_TUTORIAL_USUARIO", "Login para o sistema.");
define("TXT_TUTORIAL_GRUPO", "Grupo em que o usuário será inserido.");
define("TXT_TUTORIAL_EMAIL", "Email do usuário.");
define("TXT_TUTORIAL_SENHA", "Senha para login no sistema, deve conter pelo menos 8 caracteres, entre eles 1 letra e 1 número.");
define("TXT_TUTORIAL_CONFIRMAR_SENHA", "Confirmação da senha. Deve ser exatamente igual a senha digitada no outro campo.");
define("TXT_TUTORIAL_PERGUNTA_SENHA", "Pergunta utilizada para recuperar a senha caso ela seja esquecida/perdida.");
define("TXT_TUTORIAL_RESPOSTA_SENHA", "Resposta que validará o usuário, iniciando o processo de recuperação de senha.");
define("TXT_TUTORIAL_EXPIRA_EM", "Caso o usuário seja temporário, o mesmo será desativado na data selecionada nesse campo.");
define("TXT_TUTORIAL_FOTO", "Adicione a foto do usuário. Essa foto irá aparecer em algumas áreas do sistema como, por exemplo, a dashboard.");
define("TXT_TUTORIAL_REMOVER_FOTO", "Remova a foto do usuário. A foto utilizada será padrão.");
define("TXT_TUTORIAL_SENHA_PROVISORIA", "Se marcado, a senha atual irá servir apenas para o primeiro login no sistema, sendo obrigatório a mudança da mesma após esse login.");
define("TXT_TUTORIAL_ATIVO", "Marque/desmarque para marcar o usuário como ativo e inativo. Usuários inativos não podem logar no sistema, mas suas informações continuam salvas.");
define("TXT_TUTORIAL_MASTER", "Usuários Master possuem acesso ao sistema de IPs externos aos da Link.");
define("TXT_TUTORIAL_ENDERECO", "Informações de endereço do usuário.");
define("TXT_TUTORIAL_LOGRADOURO", "Digite parte do endereço para receber sugestões para completá-lo. Algumas informações como Cidade, Estado e Bairro são completadas automaticamente, mas devem ser conferidas.");
define("TXT_TUTORIAL_CEP", "Busque o endereço utilizando um CEP. Algumas informações como Cidade, Estado e Bairro são completadas automaticamente, mas devem ser conferidas.");
define("TXT_TUTORIAL_CONTATO", "Informações de contatos telefônicos.");
define("TXT_CAMPO_EMAIL_OBRIGATORIO", "Email inválido, favor digitar um email válido. Ex. example@example.com.br");
define("TXT_MSG_BUSCA", "Colunas de Busca: E-mail e Nome.");
