<?php
define("RTL_ATRIBUIR_CERCA", "Atribuir Cercas");
define("RTL_ATRIBUIR_PONTOS_VEICULO", "Atribuir cercas ao veículo");
define("RTL_CERCA_POLIGONO", "Cerca Polígono");
define("RTL_CERCA_ROTA", "Cerca Rotas");
define("RTL_COM_CONFIGURACAO", "Com configuração");
define("RTL_COM_MOTORISTA", "Vinculados");
define("RTL_CONFIGURAR_VEICULO", "Configurações");
define("RTL_CONSUMO_MEDIO", "Consumo Médio (Km/L)");
define("RTL_DATA_HORA_ULTIMA_POSICAO", "Última Posição");
define("RTL_ENVIAR_COMANDO", "Enviar Comando");
define("RTL_GESTAO_RFID", "Gestão de RFID");
define("RTL_MODIFICAR_VEICULO", "Modificar Veículo");
define("RTL_MOTORISTA", "Motorista");
define("RTL_MOTORISTAS_CADASTRADOS", "Motoristas x Veículos");
define("RTL_ORDEM", "Ordem");
define("RTL_PONTO_INTERESSE", "Ponto de Interesse");
define("RTL_RPM_VERDE", "RPM Faixa Verde");
define("RTL_RPM_AMARELO", "RPM Faixa Amarela");
define("RTL_RPM_VERMELHO", "RPM Faixa Vermelha");
define("RTL_SEM_CONFIGURACAO", "Sem configuração");
define("RTL_SEM_MOTORISTA", "Desvinculados");
define("RTL_TEMPO_MARCHA_LENTA", "Tempo da Marcha Lenta (minutos)");
define("RTL_VELOCIDADE_CHUVA", "Velocidade Máxima na Chuva (Km/H)");
define("RTL_VEICULOS_CONFIGURADOS", "Veículos com configuração extra");
define("RTL_VEICULOS", "Veículos");
define("RTL_SELECIONAR_ICONE", "Selecionar ícone");
define("RTL_VALIDADE_CNH_VINCULADOS", "CNH de motoristas vinculados");
define("RTL_VENCEM_ATE_60_DIAS", "Vencimento em até 60 dias");
define("RTL_VENCIDAS", "CNH vencidas");
define("RTL_VIGENCIA_NORMAL", "Vigência normal");
define("RTL_VELOCIDADE_MAXIMA", "Vel. máx");
define("RTL_DATA_HORA_ULTIMA_POSICAO", "Ultima posição");
define("RTL_QUILOMETRAGEM_DO_DIA", "Km do dia");
define("RTL_CERCAS_VINCULADAS", "N° Cercas");
define("RTL_LIGADO", "Ligado");
define("RTL_DESLIGADO", "Desligado");
define("RTL_METAS", "Metas");
define("RTL_CARGA_HORARIA", "Carga horária");
define("RTL_INICIO_JORNADA", "Início de jornada");
define("RTL_INICIO_INTERVALO", "Início de intervalo");
define("RTL_FIM_INTERVALO", "Fim de intervalo");
define("RTL_FIM_JORNADA", "Fim de jornada");
define("RTL_PRESSAO_OLEO", "Pressão do óleo mínima (psi)");
define("RTL_TEMPERATURA_MOTOR", "Temperatura do motor (°C)");
define("RTL_TEMPO_PARADO_MOTOR_LIGADO", "Tempo parado com motor ligado (minutos)");
define("TXT_COMANDO_ENVIADO_OUTRO_RFID", "Comando enviado para outro RFID!");
define("RTL_RASTREADOR_SEM_COMANDO", "Esse rastreador não possui esse comando.");
define("RTL_CUSTO_MEDIO_LITRO", "Custo médio por litro de combustível");
define("RTL_COPIAR_DIA", "Copiar para todos os dias?");
define("RTL_MOTORISTA_ATIVO_DESDE", "Motorista ativo desde");
define("RTL_DADOS_VEICULO", "Dados do veículo");
define("RTL_HISTORICO_MOTORISTAS", "Histórico de motoristas");
define("RTL_PAR_VELOCIDADE", "Velocidade");
define("RTL_PAR_RPM", "RPM");
define("RTL_PAR_CONSUMO_MEDIO", "Consumo médio");
define("RTL_PAR_TEMPERATURA_MOTOR", "Temperatura do motor");
define("RTL_PAR_LUZ_BAIXA", "Luz baixa");
define("RTL_PAR_VELOCIDADE_CHUVA", "Velocidade na chuva");
define("RTL_PAR_PRESSAO_OLEO", "Pressão de óleo");
define("RTL_PAR_TOTAL_PONTOS", "Total de pontos");
define("RTL_PARAMETROS_PONTUACAO", "Peso de pontuação");
define("RTL_TEMPERATURA_MAXIMA", "Temperatura máxima");
define("RTL_TEMPERATURA_MINIMA", "Temperatura mínima");
define("RTL_UMIDADE_MAXIMA", "Umidade máxima");
define("RTL_UMIDADE_MINIMA", "Umidade mínima");
define("RTL_VELOCIDADE_LIMITE", "Validar a partir de... (km/h)");
define("RTL_VALIDAR_PORTA", "Validar porta?");
define("RTL_PARAMETROS_TEMPERATURA", "Parâmetros de temperatura");
define("RTL_HOMOLOGACAO_SENSOR", "Homologação de sensores");
define("RTL_ENVIAR_ARQUIVO", "Enviar arquivo");
define("RTL_BAIXAR_ARQUIVO", "Baixar arquivo");
define("RTL_SELECIONE_ARQUIVO", "Selecione o arquivo");
define("RTL_CENTRO_CUSTO", "Centro de custos");
define("RTL_CONSUMO_MEDIO_HORA", "Consumo médio por hora");

define("TXT_ALERT_SUCESSO_VINCULO_CERCAS", "As alterações para a cerca selecionada foram realizadas com sucesso.<br/>Gostaria de continuar fazendo alterações?");
define("TXT_CAMPO_VAZIO", "Existem campos vazios. <br/>Preencha ou delete-os antes de salvar.<br/>");
define("TXT_CAMPOS_VAZIOS", "Existem campos vazios. <br/>Preencha-os antes de salvar.<br/>");
define("TXT_COMANDO_ENVIADO", "Comando já enviado");
define("TXT_COMANDO_NAO_ENVIADO", "Comando ainda não enviado");
define("TXT_CONFIRMAR_REMOCAO_LINHA", "Deseja realmente remover essa linha? <br/>A ação será transmitida para equipamento e não poderá ser desfeita!");
define("TXT_CONFIRMAR_ESTRUTURA", "Ao salvar a estrutura, os comandos deverão ser reenviados.<br/>Caso não houve alteração na estrutura (adição ou remoção de motoristas), não há necessidade de salvar.<br/>Neste caso, apenas feche a janela.<br/>Tem certeza que deseja salvar a estrutura?");
define("TXT_ESTRUTURA_ALTERADA", "A estrutura do comando foi alterada.<br/> Salve antes de enviar!");
define("TXT_LIMITE_MOTORISTAS", "Limite de motoristas excedido!");
define("TXT_MOTORISTA_NAO_SALVO", "Esse motorista ainda não foi cadastrado!<br/>Salve antes de enviar o comando.");
define("TXT_MOTORISTA_NAO_SALVO_BTN", "Salve o motorista antes de enviar o comando.");
define("TXT_SELECIONE_MOTORISTA", "Certifique-se de selecionar o motorista antes de adicionar novos motoristas.");
define("TXT_SELECIONE_TIPO_VEICULO", "Selecione um tipo de veículo");
define("TXT_TIPO_ALTERADO", "Tipo do veículo alterado");
define("TXT_ALERTA_SOBREPOSICAO", "Enviar um arquivo para um veículo que já possui arquivo de homologação irá sobrepor o antigo.");


//defines dos rótulos do tutorial
define("TXT_TUTORIAL_MOTORISTAS", "Gráfico de motoristas vinculados a veículos.");
define("TXT_TUTORIAL_CNH", "Gráfico de vigência de CNH para motoristas em atividade.");
define("TXT_TUTORIAL_CONFIGURADOS", "Gráfico de veículos com configuração extra.");
define("TXT_TUTORIAL_VERDE", "RPM máximo aceitável para faixa verde.");
define("TXT_TUTORIAL_AMARELO", "RPM máximo aceitável para faixa amarela.");
define("TXT_TUTORIAL_VERMELHO", "RPM máximo aceitável para faixa vermelha.");
define("TXT_TUTORIAL_CHUVA", "Velocidade máxima permitida para chuva.");
define("TXT_TUTORIAL_MARCHA_LENTA", "Tempo em minutos aceitável para marcha lenta.");
define("TXT_TUTORIAL_CONSUMO", "Consumo médio de combustível em Km/l.");
define("RTL_PRESSAO_OLEO_TUTORIAL", "Pressão do óleo.");
define("TXT_TUTORIAL_PRESSAO_OLEO", "Pressão mínima do óleo.");
define("TXT_TUTORIAL_TEMPERATURA_MOTOR", "Temperatura ideal de funcionamento do motor.");
define("RTL_TUTORIAL_MOTOR", "Temperatura ideal.");
define("RTL_TUTORIAL_MOTOR_LIGADO", "Tempo do motor ligado.");
define("TXT_TUTORIAL_MOTOR_LIGADO", "Escolha o tempo do motor parado em minutos.");
define("TXT_TUTORIAL_DIAS_SEMANA", "Escolha os dias da semana.");
define("TXT_TUTORIAL_DIAS", "Dias da semana.");
define("TXT_TUTORIAL_JORNADAS", "Defina nesses campos os horarios das jornadas e horarios de intervalo.");
define("TXT_TUTORIAL_JORNADAS_INTERVALO", "Jornadas e Intervalo.");
define("TXT_TUTORIAL_DISPONIVEIS", "Selecione o tipo da cerca para ver a listagem de cercas disponíveis para vincular ao veículo.");
define("TXT_TUTORIAL_SELECIONADOS", "Com o tipo da cerca selecionada, aqui serão listados as cercas já vinculadas.");

define("TXT_TUTORIAL_ICONE", "Selecione os ícones para veiculo ligado e desligado. Esses ícones irão aparecer em lugares como a central de monitoramento e outros mapas.");
define("TXT_TUTORIAL_MOTORISTA", "Vincule o motorista ao veículo.");
define("TXT_TUTORIAL_REGIAO", "Vincule um veículo a uma região.");
define("TXT_TUTORIAL_COMPLEMENTO", "Complemento da placa do veículo que será usado nas pesquisas de veículo.");
define("TXT_TUTORIAL_RESPONSAVEL", "Responsável pelo veículo.");
define("TXT_TUTORIAL_VELOCIDADE_MAXIMA", "Velocidade máxima permitida para o veículo.");
define("TXT_TUTORIAL_ORIGEM", "Origem do veículo.");
define("TXT_TUTORIAL_DESTINO", "Destino do veículo.");
define("TXT_TUTORIAL_OBSERVACAO", "Adicione uma observação ao veículo.");
define("TXT_TUTORIAL_VISUALIZACAO", "Selecione o tipo de visualização desejada.");
define("TXT_TUTORIAL_BUSCA", "Digite algo para buscar e aperte enter ou clique na lupa para iniciar a pesquisa. Dessa forma, serão filtrados registros que contenham o texto buscado.");
define("TXT_TUTORIAL_LISTAGEM", "Clique em colunas que possuem as setas para ordenar os registros. Os ícones da última coluna da direita possuem ações para cada registro.");
define("TXT_TUTORIAL_ABA_LISTAGEM", "Listagem dos veículos.");
define("TXT_MSG_BUSCA", "Colunas de Busca: Rótulo, Motorista, Cliente, Complemento da placa.");

