<?
define("RTL_ATE_50KM", "Até 50 km/h");
define("RTL_DE_50_A_100KM", "de 50 a 100 km/h");
define("ROTULO_VELOCIDADE_EVENTOS", "Velocidades Excedidas Eventos");
define("RTL_EMAIL", "E-mail");
define("RTL_EVENTO", "Evento");
define("RTL_EVENTOS_ATIVOS", "Eventos Ativos");
define("RTL_EVENTOS_FINALIZADOS", "Eventos Finalizados");
define("RTL_EVENTOS_GERADOS", "Eventos Gerados");
define("RTL_EVENTOS_GERADOS_FINALIZADOS", "Eventos Gerados x Eventos Finalizados");
define("RTL_FINALIZAR_EVENTO", "Finalizar Evento");
define("RTL_GERAR_RELATORIO", "Gerar Relatório");
define("RTL_LISTAGEM_VEICULOS_VELOCIDADE_EXCEDIDA", "Listagem de Veículos");
define("RTL_LOGRADOURO", "Logradouro");
define("RTL_MAIOR_100KM", "maior que 100 km/h");
define("RTL_MAIORES_VELOCIDADES", "Maiores velocidades");
define("RTL_MODIFICAR", "Modificar Velocidade Máxima");
define("RTL_MOTORISTA", "Motorista");
define("RTL_NOME_MOTORISTA", "Motorista");
define("RTL_NUMERO_SERIE", "Número de Série do Rastreador");
define("RTL_PANICO", "Pânico");
define("RTL_PLACA_ROTULO", "Placa/Rótulo");
define("RTL_POSICOES", "Posições por Velocidade");
define("RTL_RELATORIO", "Relatório");
define("RTL_SMS", "SMS");
define("RTL_ULTIMA_SEMANA", "Última Semana");
define("RTL_ULTIMOS_4_MESES", "Últimos 4 Meses");
define("RTL_VEICULO", "Veículo");
define("RTL_VEICULOS", "Veículos");
define("RTL_VELOCIDADE", "Velocidade");
define("RTL_VELOCIDADE", "Velocidade");
define("RTL_VELOCIDADE_EXCEDIDA", "Velocidade Excedida");
define("RTL_VELOCIDADE_MAXIMA", "Velocidade Máxima");
define("TXT_ALERT_SUCESSO_MODIFICAR", "Sucesso ao modificar o registro.");
define("TXT_CONFIRMA_FINALIZAR_EVENTO", "Deseja realmente finalizar este evento?");
define("TXT_ERRO_DATA_HORA_FIM", "Selecione uma data/hora final para gerar o relatório<br/>");
define("TXT_ERRO_DATA_HORA_INICIO", "Selecione uma data/hora inicial para gerar o relatório<br/>");
define("TXT_ERRO_ID_VEICULO_GRUPO", "Selecione um grupo ou um veículo para gerar o relatório<br/>");
define("TXT_ERRO_INICIO_MAIOR_FIM", "A data inicial é posterior à data final.<br/>");
define("TXT_SALVO_AUTOMATICAMENTE", "As configurações são salvas automaticamente.");
define("RTL_VELOCIDADE_MINIMA", "Velocidade mínima");
define("RTL_VELOCIDADE_REGISTRADA", "Velocidade registrada");
define("RTL_VELOCIDADE_LIMITE", "Velocidade limite");
define("RTL_RELATORIO_VELOCIDADES", "Relatório Velocidades");
define("TXT_VEL_MINIMA", "Você pode selecionar a velocidade mínima a ser exibida neste relatório. Para exibir com base na velocidade limite definida na aba CONFIGURAÇÃO deixe o campo vazio");
define("RTL_VELOCIDADE_ACIMA_DE", "Velocidade acima de");
define("RTL_TEMPO_ACIMA_DE", "Tempo acima de");

//defines dos rótulos do tutorial
define("TXT_TUTORIAL_POSICOES", "Quantidade de posições por limite de velocidade.");
define("TXT_TUTORIAL_MAIORES_VELOCIDADES", "Ranking dos veículos que alcançaram maior pico de velocidade na data corrente.");
define("TXT_TUTORIAL_GRUPO", "Selecione o veículo pelo qual gostaria de filtrar o relatório.");
define("TXT_TUTORIAL_VEICULO", "Selecione o veículo pelo qual gostaria de filtrar o relatório.");
define("TXT_TUTORIAL_DATA_HORA_INICIAL", " Selecione a data inicial que deseja visualizar.");
define("TXT_TUTORIAL_DATA_HORA_FINAL", " Selecione a data final que deseja visualizar.");
define("TXT_TUTORIAL_VELOCIDADE_MAXIMA", "Velocidade máxima do veículo previamente cadastrada pelo usuário.");
define("TXT_TUTORIAL_EVENTO", "Gerar eventos.");
define("TXT_TUTORIAL_EMAIL", "Enviar eventos por e-mail.");
define("TXT_TUTORIAL_SMS", " Enviar eventos por SMS.");
define("TXT_TUTORIAL_LISTAGEM", "Lista de eventos de velocidades excedidas. Você terá a opção de finalizar esses eventos a qualquer momento através do ícone finalizar evento à direita de cada listagem.");
define("TXT_MSG_BUSCA", "Colunas de Busca: Placa/Rótulo e Grupo.");
define("TXT_MSG_BUSCA2", "Colunas de Busca: Placa/Rótulo, Grupo e Motorista.");
define("TXT_LIMITE_DIAS_GRUPO", "Pesquisa por grupo limita a busca em 7 dias");
define("TXT_LIMITE_DIAS_VEICULO", "Pesquisa por veículo limita a busca em 30 dias");
